Repository RPTools/maptool, pull requests merged in 2019-03, with the labels that each got.

#267 Sentry.io releases config
  .travis.yml
Labels: 1, enhancement, low

#294 Catch abort
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/MapToolVariableResolver.java
Labels: enhancement

#319 Fix #50 unit per cell as double
  src/main/java/net/rptools/maptool/client/functions/TokenLocationFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenMoveFunctions.java
  src/main/java/net/rptools/maptool/client/tool/MeasureTool.java
  src/main/java/net/rptools/maptool/client/tool/ToolHelper.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RadiusTemplateTool.java
  src/main/java/net/rptools/maptool/client/ui/MapPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/walker/NaiveWalker.java
  src/main/java/net/rptools/maptool/client/walker/ZoneWalker.java
  src/main/java/net/rptools/maptool/client/walker/astar/AbstractAStarWalker.java
  src/main/java/net/rptools/maptool/model/Zone.java
Labels: Claimed

#306 Token edit opacity preview 289
  src/main/java/net/rptools/maptool/client/ui/token/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/ImageAssetPanel.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
Labels: feature, in progress

#307 Add delete keys 255
  src/main/java/net/rptools/maptool/client/ui/MapToolFrame.java
Labels: feature, in progress

#399 Fixes #398. Changed addition of newline character to be at cursor…
  CHANGE_LOG.md
  src/main/java/net/rptools/maptool/client/ui/commandpanel/CommandPanel.java
Labels: 1, feature, low

#393 Fix #392 add support for double unitsPerCell in preferences
  CHANGE_LOG.md
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/ui/PreferencesDialog.java
Labels: 1, feature, low

#377 fix getViewArea for cells
  CHANGE_LOG.md
  src/main/java/net/rptools/maptool/client/functions/ZoomFunctions.java
Labels: 1, bug, low

#311 Fix #106 add reset size popup menu entry
  src/main/java/net/rptools/maptool/client/functions/TokenPropertyFunctions.java
  src/main/java/net/rptools/maptool/client/ui/AbstractTokenPopupMenu.java
Labels: claimed, feature, in progress, macro changes

#305 Fix #292 wrong URLs in Help menu
  src/dist/README.pod
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: bug
