Repository RPTools/maptool, pull requests merged in 2019-10, with the labels that each got.

#757 Fix prompt to "update" to old version when on pre-release
  src/main/java/net/rptools/maptool/client/AppUpdate.java
  src/main/resources/github.properties
Labels: bug, feature, low

#765 Emergency fix for NPE on Mac OS
  src/main/java/net/rptools/maptool/client/tool/DefaultTool.java
Labels: bug

#849 Closes #848 - Add File Sync Directory to getInfo("client") macro
  src/main/java/net/rptools/maptool/client/functions/getInfoFunction.java
Labels: S, feature, low, macro changes

#851 Closes #850 - Add log.trace to log macro group
  src/main/java/net/rptools/maptool/client/functions/LogFunctions.java
Labels: S, feature, low, macro changes
