Repository RPTools/maptool, pull requests merged in 2019-05, with the labels that each got.

#460 152 change log update
  CHANGE_LOG.md
Labels: documentation

#466 Feature macro editor themes
  src/main/java/net/rptools/lib/FileUtil.java
  src/main/java/net/rptools/maptool/client/AppConstants.java
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/AppSetup.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/ui/MacroButtonDialog.java
  src/main/java/net/rptools/maptool/client/ui/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/syntax/MapToolScriptAutoComplete.java
  src/main/java/net/rptools/maptool/client/ui/syntax/MapToolScriptSyntax.java
  src/main/resources/net/rptools/maptool/client/ui/forms/preferencesDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/Dark.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/Default Alt.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/Default.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/Eclipse.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/Idea.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/Large Text.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/Monokai.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/Nerps (Dark).xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/Nerps.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/Visual Studio.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/nerps-dark.xml
  src/main/resources/net/rptools/maptool/client/ui/syntax/themes/theme.dtd
Labels: 3, feature, macro changes

#482 Fix for tokens getting wrong size on hex maps.
  src/main/java/net/rptools/maptool/model/HexGrid.java
Labels: bug
