Repository RPTools/maptool, pull requests merged in 2019-09, with the labels that each got.

#641 Change wrong nb of parameters error messages to display function name
  build.gradle
  src/main/java/net/rptools/maptool/client/functions/InputFunction.java
  src/main/java/net/rptools/maptool/client/functions/ReturnFunction.java
  src/main/java/net/rptools/maptool/client/functions/StrListFunctions.java
  src/main/java/net/rptools/maptool/client/functions/StrPropFunctions.java
  src/main/java/net/rptools/maptool/client/functions/UserDefinedMacroFunctions.java
Labels: 1, feature, low

#648 Consolidate methods checkNumberOfParameters and getTokenFromParam
  src/main/java/net/rptools/maptool/client/functions/DrawingFunctions.java
  src/main/java/net/rptools/maptool/client/functions/DrawingGetterFunctions.java
  src/main/java/net/rptools/maptool/client/functions/DrawingMiscFunctions.java
  src/main/java/net/rptools/maptool/client/functions/DrawingSetterFunctions.java
  src/main/java/net/rptools/maptool/client/functions/LookupTableFunction.java
  src/main/java/net/rptools/maptool/client/functions/MapFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenImage.java
  src/main/java/net/rptools/maptool/client/functions/TokenLocationFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenNameFunction.java
  src/main/java/net/rptools/maptool/client/functions/TokenPropertyFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenSightFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenStateFunction.java
Labels: S, macro changes, refactor

#662 Fix bring to front/send to back need to be done twice
  src/main/java/net/rptools/maptool/server/ServerMethodHandler.java
Labels: S, bug, low

#657 Add json.path.read, and json.path.add/set/put/delete (based on jayway)
  build.gradle
  src/main/java/net/rptools/maptool/client/functions/JSONMacroFunctions.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: M, feature, macro changes

#666 Add new Server Option for GM to Reveal FoW for Unowned Tokens
  build-resources/abeille-maptool-forms.jfpr
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/tool/FacingTool.java
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
  src/main/java/net/rptools/maptool/client/ui/StartServerDialogPreferences.java
  src/main/java/net/rptools/maptool/server/ServerPolicy.java
  src/main/resources/net/rptools/maptool/client/ui/forms/startServerDialog.xml
Labels: M, feature, low

#611 Debounce/throttle rapid ZoneRenderer calls to repaint()
  src/main/java/net/rptools/maptool/client/DebounceExecutor.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
Labels: M, feature, low

#686 Change getTokens to be much faster with area option
  src/main/java/net/rptools/maptool/client/functions/FindTokenFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenLocationFunctions.java
Labels: low, performance

#691 ImagePanel QOL improvements
  src/main/java/net/rptools/lib/swing/ImagePanel.java
Labels: low, performance

#695 Resolve #694 -- Fix asset panel scaling
  src/main/java/net/rptools/lib/swing/ImagePanel.java
Labels: M, bug

#721 Add parameter "players" and "delim" to execLink
  src/main/java/net/rptools/maptool/client/ClientCommand.java
  src/main/java/net/rptools/maptool/client/ClientMethodHandler.java
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/client/functions/MacroLinkFunction.java
  src/main/java/net/rptools/maptool/server/ServerCommand.java
  src/main/java/net/rptools/maptool/server/ServerMethodHandler.java
Labels: M, macro changes, medium

#723 Add scrolling to Select Map menu
  src/main/java/net/rptools/maptool/client/ui/JScrollPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/ZoneSelectionPopup.java
Labels: S, feature, low

#747 Update parser to 1.5.5
  build.gradle
Labels: bug, build-configuration, high

#752 Fix for jpeg2000 image extraction for PDF's
  src/main/java/net/rptools/maptool/client/MapTool.java
Labels: bug
