Repository RPTools/maptool, pull requests merged in 2019-04, with the labels that each got.

#415 Add "getDrawingInfo()" function
  src/main/java/net/rptools/maptool/client/functions/DrawingFunctions.java
  src/main/java/net/rptools/maptool/client/functions/DrawingGetterFunctions.java
Labels: 3, feature, low, macro changes

#418 Add movedOverDrawing() function
  src/main/java/net/rptools/maptool/client/functions/DrawingMiscFunctions.java
  src/main/java/net/rptools/maptool/model/drawing/DrawablesGroup.java
Labels: 1, feature, low, macro changes

#421 Added Dependency for new Dice Lib and a couple functions to get what was rolled
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/functions/LastRolledFunction.java
Labels: 5, feature, macro changes

#414 Add Line Cell template
  src/main/java/net/rptools/maptool/client/tool/drawing/LineCellTemplateTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RadiusCellTemplateTool.java
  src/main/java/net/rptools/maptool/client/ui/ToolbarPanel.java
  src/main/java/net/rptools/maptool/model/drawing/AbstractTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/LineCellTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/RadiusCellTemplate.java
Labels: 1, feature, low

#427 Add two new previous roll functions
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/functions/LastRolledFunction.java
Labels: 1, macro changes

#431 Feature Enhancement - Base64 macro functions
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/functions/Base64Functions.java
Labels: feature, macro changes

#440 Feature udf tooltip
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/functions/AdditionalFunctionDescription.java
  src/main/java/net/rptools/maptool/client/functions/FindTokenFunctions.java
  src/main/java/net/rptools/maptool/client/functions/UserDefinedMacroFunctions.java
  src/main/java/net/rptools/maptool/client/ui/MacroButtonDialog.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttongroups/ButtonGroup.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttons/MacroButton.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttons/MacroButtonPrefs.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttons/TransferData.java
  src/main/java/net/rptools/maptool/client/ui/syntax/MapToolScriptAutoComplete.java
  src/main/java/net/rptools/maptool/model/MacroButtonProperties.java
  src/main/resources/net/rptools/maptool/client/ui/forms/macroButtonDialog.xml
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: 1, feature, low, macro changes

#433 Feature logging
  .travis.yml
  build.gradle
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/AppState.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/functions/LogFunctions.java
  src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java
  src/main/java/net/rptools/maptool/client/swing/AppHomeDiskSpaceStatusBar.java
  src/main/java/net/rptools/maptool/client/swing/AssetCacheStatusBar.java
  src/main/java/net/rptools/maptool/client/swing/ImageCacheStatusBar.java
  src/main/java/net/rptools/maptool/client/ui/AppMenuBar.java
  src/main/java/net/rptools/maptool/client/ui/logger/JTextAreaAppender.java
  src/main/java/net/rptools/maptool/client/ui/logger/LogConsoleFrame.java
  src/main/resources/log4j2.xml
  src/main/resources/net/rptools/maptool/client/image/log4j_icon.png
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: 3, feature, macro changes, medium

#447 Fix MapTool not logging when ran from uberJar or installed versions
  build.gradle
  src/main/resources/log4j2.xml
Labels: 1, bug, medium
