Repository RPTools/maptool, pull requests merged in 2020-03, with the labels that each got.

#1332 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
Labels: translations

#1336 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
Labels: translations

#1357 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
Labels: translations

#1360 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
Labels: translations

#1371 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1374 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
Labels: translations

#1377 Update README.md
  README.md
Labels: documentation

#1389 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
Labels: translations

#1390 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
Labels: translations

#1404 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
Labels: translations

#1435 Feature: Token VBL simplification
  build-resources/abeille-maptool-forms.jfpr
  src/main/java/net/rptools/maptool/client/functions/VBL_Functions.java
  src/main/java/net/rptools/maptool/client/ui/token/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/TokenVblPanel.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/TokenVBL.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/resources/net/rptools/maptool/client/image/color-picker-256.png
  src/main/resources/net/rptools/maptool/client/image/color-picker-32.png
  src/main/resources/net/rptools/maptool/client/ui/forms/tokenPropertiesDialog.xml
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: M, feature, macro changes
