Repository RPTools/maptool, pull requests merged in 2020-04, with the labels that each got.

#1436 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1452 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
Labels: translations

#1480 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
Labels: translations

#1488 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
Labels: translations

#1493 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
Labels: translations

#1494 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
Labels: translations

#1499 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1521 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
Labels: translations

#1547 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1549 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1555 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1577 Adds option to extract all pages as images from pdfs in the resource …
  src/main/java/net/rptools/lib/image/ImageUtil.java
  src/main/java/net/rptools/maptool/client/ui/assetpanel/AssetPanel.java
  src/main/java/net/rptools/maptool/client/ui/assetpanel/ImageFileImagePanelModel.java
  src/main/java/net/rptools/maptool/util/ExtractImagesFromPDF.java
  src/main/java/net/rptools/maptool/util/ImageManager.java
  src/main/java/net/rptools/maptool/util/PersistenceUtil.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: documentation, feature

#1581 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1591 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1592 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1609 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1611 Add I18N support to Preference dialog
  src/main/resources/net/rptools/maptool/client/ui/forms/preferencesDialog.xml
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: translations

#1612 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
Labels: translations

#1615 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1625 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
Labels: translations

#1626 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1628 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1632 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1636 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1647 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1651 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1656 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1661 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
Labels: translations

#1662 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
Labels: translations

#1622 Add more token sizes, up 10x10.
  src/main/java/net/rptools/maptool/tool/TokenFootprintCreator.java
  src/main/resources/net/rptools/maptool/model/squareGridFootprints.xml
Labels: ON HOLD

#1684 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1693 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
Labels: translations

#1695 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1697 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
Labels: translations

#1702 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
Labels: translations

#1723 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1731 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations
