Repository RPTools/maptool, pull requests merged in 2020-02, with the labels that each got.

#1209 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
Labels: translations

#1212 Feature mbl
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/AppStyle.java
  src/main/java/net/rptools/maptool/client/ClientMethodHandler.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/client/tool/drawing/AbstractDrawingTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/CrossTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DiamondTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowDiamondTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowOvalTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowRectangleTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/OvalTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/PolygonTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RectangleTopologyTool.java
  src/main/java/net/rptools/maptool/client/ui/ToolbarPanel.java
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/TokenVBL.java
  src/main/java/net/rptools/maptool/client/walker/astar/AbstractAStarWalker.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/server/ServerCommand.java
  src/main/java/net/rptools/maptool/server/ServerMethodHandler.java
  src/main/resources/net/rptools/maptool/client/image/tool/ignore-vbl-on-move.png
  src/main/resources/net/rptools/maptool/client/image/tool/mbl-only.png
  src/main/resources/net/rptools/maptool/client/image/tool/mbl-vbl-on.png
  src/main/resources/net/rptools/maptool/client/image/tool/use-vbl-on-move.png
  src/main/resources/net/rptools/maptool/client/image/tool/vbl-only.png
Labels: M, feature

#1214 Feature token vbl simplification
  src/main/java/net/rptools/maptool/client/ui/token/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/TokenVBL.java
Labels: M, documentation, feature, macro changes

#1224 Fix java doc warnings part 1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/AppUtil.java
  src/main/java/net/rptools/maptool/client/MRUCampaignManager.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/MapToolUtil.java
  src/main/java/net/rptools/maptool/client/MapToolVariableResolver.java
  src/main/java/net/rptools/maptool/client/RemoteFileDownloader.java
  src/main/java/net/rptools/maptool/client/ScreenPoint.java
  src/main/java/net/rptools/maptool/client/TransferableHelper.java
  src/main/java/net/rptools/maptool/client/functions/AssertFunction.java
  src/main/java/net/rptools/maptool/client/functions/DrawingFunctions.java
  src/main/java/net/rptools/maptool/client/functions/EvalMacroFunctions.java
  src/main/java/net/rptools/maptool/client/functions/InputFunction.java
  src/main/java/net/rptools/maptool/client/functions/MacroLinkFunction.java
  src/main/java/net/rptools/maptool/client/functions/StrListFunctions.java
  src/main/java/net/rptools/maptool/client/functions/StrPropFunctions.java
  src/main/java/net/rptools/maptool/client/functions/StringFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenInitFunction.java
  src/main/java/net/rptools/maptool/client/functions/TokenNameFunction.java
  src/main/java/net/rptools/maptool/client/functions/TokenVisibleFunction.java
  src/main/java/net/rptools/maptool/client/tool/drawing/AbstractLineTool.java
  src/main/java/net/rptools/maptool/client/ui/commandpanel/CommandPanel.java
  src/main/java/net/rptools/maptool/language/I18N.java
  src/main/java/net/rptools/maptool/model/Grid.java
Labels: code maintenance

#1221 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1227 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1230 Fix for various TokenMoveFunctions that rely on pathPointsToJSONArray…
  src/main/java/net/rptools/maptool/client/functions/TokenMoveFunctions.java
Labels: bug

#1229 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
Labels: translations

#1232 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1251 Revert "Revert "Merge branch 'feature-mbl'
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/AppStyle.java
  src/main/java/net/rptools/maptool/client/ClientMethodHandler.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/client/tool/drawing/AbstractDrawingTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/CrossTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DiamondTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowDiamondTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowOvalTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowRectangleTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/OvalTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/PolygonTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RectangleTopologyTool.java
  src/main/java/net/rptools/maptool/client/ui/ToolbarPanel.java
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/TokenVBL.java
  src/main/java/net/rptools/maptool/client/walker/astar/AbstractAStarWalker.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/server/ServerCommand.java
  src/main/java/net/rptools/maptool/server/ServerMethodHandler.java
  src/main/resources/net/rptools/maptool/client/image/tool/ignore-vbl-on-move.png
  src/main/resources/net/rptools/maptool/client/image/tool/mbl-only.png
  src/main/resources/net/rptools/maptool/client/image/tool/mbl-vbl-on.png
  src/main/resources/net/rptools/maptool/client/image/tool/use-vbl-on-move.png
  src/main/resources/net/rptools/maptool/client/image/tool/vbl-only.png
Labels: M, feature

#1242 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1254 Fix md5key thread safety
  src/main/java/net/rptools/lib/MD5Key.java
Labels: thread-safety

#1256 Update .appveyor.yml
  .appveyor.yml
Labels: build-configuration

#1275 Feature GRID support for Hexes
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/HexGrid.java
  src/main/java/net/rptools/maptool/model/HexGridHorizontal.java
  src/main/java/net/rptools/maptool/model/HexGridVertical.java
Labels: bug, feature

#1261 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1287 Toolbar refactor for AI & Topology Section tools
  src/main/java/net/rptools/maptool/client/ClientMethodHandler.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/tool/AI_Tool.java
  src/main/java/net/rptools/maptool/client/tool/AI_UseVblTool.java
  src/main/java/net/rptools/maptool/client/tool/DrawTopologySelectionTool.java
  src/main/java/net/rptools/maptool/client/ui/Tool.java
  src/main/java/net/rptools/maptool/client/ui/ToolbarPanel.java
  src/main/java/net/rptools/maptool/client/ui/Toolbox.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/walker/astar/AbstractAStarWalker.java
  src/main/java/net/rptools/maptool/server/ServerMethodHandler.java
  src/main/java/net/rptools/maptool/server/ServerPolicy.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug, low, macro changes

#1290 Rehost JDK used for travis CI
  .travis.yml
Labels: build-configuration

#1297 Bug fix for NPE when Hero Lab XML data missing
  src/main/java/net/rptools/maptool/util/ExtractHeroLab.java
Labels: S, bug

#1279 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1306 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1310 Points to the latest version of maptool-resources with the additional maps
  build.gradle
Labels: build-configuration

#1311 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
Labels: translations

#1314 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1321 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1322 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations
