Repository RPTools/maptool, pull requests merged in 2020-01, with the labels that each got.

#1070 AutoSaveManager message fix
  src/main/java/net/rptools/maptool/client/AutoSaveManager.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#1068 More Terrain Modifier choices
  src/main/java/net/rptools/maptool/client/tool/ToolHelper.java
  src/main/java/net/rptools/maptool/client/ui/token/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/RenderPathWorker.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/walker/AbstractZoneWalker.java
  src/main/java/net/rptools/maptool/client/walker/ZoneWalker.java
  src/main/java/net/rptools/maptool/client/walker/astar/AStarCellPoint.java
  src/main/java/net/rptools/maptool/client/walker/astar/AbstractAStarWalker.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/resources/net/rptools/maptool/client/ui/forms/tokenPropertiesDialog.xml
Labels: M, documentation, feature

#1110 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1128 Fix broken loggers
  build.gradle
Labels: bug

#1115 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: ON HOLD, translations

#1136 Update Terrain Modifier functions
  src/main/java/net/rptools/maptool/client/functions/TokenTerrainModifierFunctions.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: M, documentation, feature, macro changes

#1138 Minor rolling log archive fix
  build.gradle
  src/main/resources/log4j2.xml
Labels: S, bug, low

#1164 New command line argument option -load or -l
  src/main/java/net/rptools/maptool/client/MapTool.java
Labels: S, feature, low

#1179 Fixes AI Terrain Modifier distance calculations
  src/main/java/net/rptools/maptool/client/ui/MapPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/walker/AbstractZoneWalker.java
  src/main/java/net/rptools/maptool/client/walker/astar/AStarCellPoint.java
  src/main/java/net/rptools/maptool/client/walker/astar/AbstractAStarWalker.java
  src/main/java/net/rptools/maptool/model/CellPoint.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/resources/net/rptools/maptool/client/ui/forms/mapPropertiesDialog.xml
Labels: M, bug, claimed, documentation

#1190 Fixes Token VBL and AI Pathing Conflict #456
  src/main/java/net/rptools/maptool/client/ui/zone/RenderPathWorker.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/walker/AbstractZoneWalker.java
  src/main/java/net/rptools/maptool/client/walker/ZoneWalker.java
  src/main/java/net/rptools/maptool/client/walker/astar/AbstractAStarWalker.java
  src/main/java/net/rptools/maptool/model/Token.java
Labels: S, bug, low

#1191 Last develop changes for 1.5.11
  src/main/java/net/rptools/maptool/client/ui/zone/RenderPathWorker.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/walker/AbstractZoneWalker.java
  src/main/java/net/rptools/maptool/client/walker/ZoneWalker.java
  src/main/java/net/rptools/maptool/client/walker/astar/AbstractAStarWalker.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/test/java/net/rptools/maptool/client/functions/json/JSONMacroFunctions.java
Labels: bug

#1196 No logging for unit tests
  src/test/resources/log4j2.xml
Labels: code maintenance

#1193 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1194 Remove jlayer dependency
  build.gradle
  src/main/java/net/rptools/lib/sound/SoundPlayer.java
Labels: dependencies

#1205 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations
