Repository RPTools/maptool, pull requests merged in 2020-06, with the labels that each got.

#1966 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
Labels: translations

#1969 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
Labels: translations

#1989 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
Labels: translations

#1999 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#2008 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
Labels: translations

#2011 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
Labels: translations

#2025 New Crowdin updates
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#2028 Change build and README to account for main branch rename
  .github/workflows/verify-build.yml
  README.md
Labels: build-configuration, code maintenance

#2030 Fix for some images showing up as black
  build.gradle
  src/main/java/net/rptools/lib/image/ImageUtil.java
  src/main/java/net/rptools/maptool/client/swing/HTMLPanelImageCache.java
  src/main/java/net/rptools/maptool/client/swing/ImageLoaderCache.java
Labels: bug, medium

#2035 Fix JVM cfg file loading
  .github/workflows/verify-build.yml
  src/main/java/net/rptools/maptool/client/AppUtil.java
  src/main/java/net/rptools/maptool/client/ui/PreferencesDialog.java
  src/main/java/net/rptools/maptool/util/UserJvmOptions.java
Labels: feature

#2052 New Crowdin updates
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations
