Repository RPTools/maptool, pull requests merged in 2020-05, with the labels that each got.

#1767 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1769 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
Labels: translations

#1772 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1778 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
Labels: translations

#1780 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
Labels: translations

#1786 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
Labels: translations

#1787 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1793 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1798 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1807 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
Labels: translations

#1819 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
Labels: translations

#1834 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1835 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1842 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
Labels: translations

#1854 Fixes incorrect ordering of CSS when the CSS is loaded from a macro button (eg CSS@lib:css)
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLWebViewManager.java
Labels: bug

#1865 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
Labels: translations

#1856 Resolve merge conflicts between develop and feature jdk14
  .appveyor.yml
  .github/workflows/publish.yml
  .github/workflows/verify-build.yml
  .gitignore
  .travis.yml
  build-resources/packaging-tool-user-guide.pdf
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/libpackager.so
  lib/packager.jar
  package/associations.properties
  package/linux/MapTool-Dev-Release.png
  package/macosx/MapTool-Dev-Release.icns
  package/macosx/maptool-icon.icns
  package/windows/MapTool-Dev-Release.ico
  package/windows/MapTool.iss.template
  package/windows/config/MapTool.ico
  package/windows/config/WixUIDialogBmp.bmp
  package/windows/config/WixUIDialogBmp.png
  src/main/java/net/rptools/maptool/client/AppUtil.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/swing/MemoryStatusBar.java
  src/main/java/net/rptools/maptool/client/swing/SplashScreen.java
  src/main/java/net/rptools/maptool/client/ui/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/EditTokenDialog.java
  src/main/java/net/rptools/maptool/util/MapToolSysInfoProvider.java
  src/main/java/net/rptools/maptool/util/UserJvmOptions.java
  src/main/java/net/rptools/maptool/util/UserJvmPrefs.java
  src/main/resources/net/rptools/maptool/client/ui/forms/preferencesDialog.xml
  src/test/resources/net/rptools/maptool/util/MapTool-Sample.cfg
Labels: deferred

#1897 Fix lumen 100 lights not working for tokens with personal light
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
Labels: bug

#1927 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: translations

#1929 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
Labels: translations

#1932 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
Labels: translations

#1953 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
Labels: translations

#1955 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
Labels: translations

#1959 New Crowdin translations
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
Labels: translations
