Repository RPTools/maptool, pull requests merged in 2023-12, with the labels that each got.

#4531 MetaMacro Functionality for GM & Campaign Panel Buttons
  src/main/java/net/rptools/maptool/client/MapToolVariableResolver.java
  src/main/java/net/rptools/maptool/client/functions/MacroFunctions.java
Labels: feature

#4517 i18n language files updated for new beam light type
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_au.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_gb.properties
Labels: feature

#4518 Implement a CodeTimer stack
  src/main/java/net/rptools/lib/CodeTimer.java
  src/main/java/net/rptools/lib/io/PackedFile.java
  src/main/java/net/rptools/maptool/client/swing/ImagePanel.java
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/panels/SelectionPanel.java
  src/main/java/net/rptools/maptool/client/ui/zone/FogUtil.java
  src/main/java/net/rptools/maptool/client/ui/zone/PartitionedDrawableRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/TokenLocation.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/util/PersistenceUtil.java
Labels: refactor

#4541 Make light source detection more consistent
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/LightsRenderer.java
  src/main/java/net/rptools/maptool/model/player/LocalPlayer.java
Labels: bug

#4545 Added second Joker to card deck
  src/main/resources/net/rptools/maptool/client/defaultTables.mtprops
Labels: feature

#4553 Add UI for defining unique lights
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.form
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/util/LightSyntax.java
  src/main/java/net/rptools/maptool/util/SightSyntax.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#4557 Fix note rendering when labels are present.
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
Labels: bug

#4558 Consistently render movement with different fog and vision settings
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
Labels: bug

#4561 Refactor EditTokenDialog.action.hero.statBlockRTextScroll i18n key.
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.form
  src/main/resources/net/rptools/maptool/client/ui/forms/tokenPropertiesDialog.xml
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/i18n_cs.properties
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_au.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_gb.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: refactor

#4516 Change BEAM lights and sights to accept width instead of arc
  src/main/java/net/rptools/maptool/client/functions/TokenLightFunctions.java
  src/main/java/net/rptools/maptool/client/functions/getInfoFunction.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/model/CampaignProperties.java
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/IsometricGrid.java
  src/main/java/net/rptools/maptool/model/Light.java
  src/main/java/net/rptools/maptool/model/LightSource.java
  src/main/java/net/rptools/maptool/model/SightType.java
  src/main/java/net/rptools/maptool/tool/LightSourceCreator.java
  src/main/java/net/rptools/maptool/util/LightSyntax.java
  src/main/java/net/rptools/maptool/util/SightSyntax.java
  src/main/proto/data_transfer_objects.proto
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#4576 Added missing colon in button CSS
  src/main/resources/net/rptools/maptool/library/builtin/mt-theme-css.hbs
Labels: bug

#4577 Simplify AreaMeta and move vision blocking algorithm into a dedicated class
  src/main/java/net/rptools/lib/GeometryUtil.java
  src/main/java/net/rptools/maptool/client/ui/zone/FogUtil.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/AreaContainer.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/AreaIsland.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/AreaMeta.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/AreaOcean.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/AreaTree.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/VisibilityInspector.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/VisibilityProblem.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/VisionBlockingAccumulator.java
Labels: refactor

#4583 Added parameter checks to metamacro functions
  src/main/java/net/rptools/maptool/client/functions/MacroFunctions.java
Labels: bug

#4589 Better encapsulated version of Zone.clearDrawables()
  src/main/java/net/rptools/maptool/client/ClientMessageHandler.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/server/ServerMessageHandler.java
Labels: bug

#4565 Revamp sight light text
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: refactor
