Repository RPTools/maptool, pull requests merged in 2023-11, with the labels that each got.

#4323 Additional JSAPI Token Functions
  src/main/java/net/rptools/maptool/client/script/javascript/api/JSAPIToken.java
  src/main/java/net/rptools/maptool/model/Token.java
Labels: bug

#4299 Cover VBL Addition
  src/main/java/net/rptools/maptool/client/AppStyle.java
  src/main/java/net/rptools/maptool/client/functions/Topology_Functions.java
  src/main/java/net/rptools/maptool/client/swing/TopologyModeSelectionPanel.java
  src/main/java/net/rptools/maptool/client/tool/drawing/AbstractDrawingTool.java
  src/main/java/net/rptools/maptool/client/ui/theme/Icons.java
  src/main/java/net/rptools/maptool/client/ui/theme/RessourceManager.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.form
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenTopologyPanel.java
  src/main/java/net/rptools/maptool/client/ui/zone/FogUtil.java
  src/main/java/net/rptools/maptool/client/ui/zone/RenderPathWorker.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/VisibilityInspector.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/VisionBlockingAccumulator.java
  src/main/java/net/rptools/maptool/client/walker/AbstractZoneWalker.java
  src/main/java/net/rptools/maptool/client/walker/ZoneWalker.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/proto/data_transfer_objects.proto
  src/main/resources/net/rptools/maptool/client/image/tool/cover-vbl-only-off.png
  src/main/resources/net/rptools/maptool/client/image/tool/cover-vbl-only.png
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#4318 onChangeMap add-on compliance, output added
  src/main/java/net/rptools/maptool/client/functions/MapFunctions.java
  src/main/java/net/rptools/maptool/client/ui/syntax/MapToolScriptSyntax.java
  src/main/java/net/rptools/maptool/events/ZoneLoadedListener.java
Labels: feature

#4327 Fix for cancelling from map export
  src/main/java/net/rptools/maptool/client/AppActions.java
Labels: bug

#4319 onMouseOver event
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/events/TokenHoverListener.java
Labels: feature

#4366 Fix For Unable to load/save campaign when running from Jar file
  src/main/java/net/rptools/maptool/client/AppUtil.java
Labels: bug

#4367 Backport the map export fix to 1.14
  src/main/java/net/rptools/maptool/client/AppActions.java
Labels: bug

#4356 Add unique light sources on tokens, and macros for manipulating them.
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/client/functions/TokenLightFunctions.java
  src/main/java/net/rptools/maptool/client/ui/AbstractTokenPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/LightSourceIconOverlay.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/model/AttachedLightSource.java
  src/main/java/net/rptools/maptool/model/Campaign.java
  src/main/java/net/rptools/maptool/model/Light.java
  src/main/java/net/rptools/maptool/model/LightSource.java
  src/main/java/net/rptools/maptool/model/SightType.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/server/ServerCommand.java
  src/main/java/net/rptools/maptool/tool/LightSourceCreator.java
  src/main/proto/data_transfer_objects.proto
Labels: feature

#4377 Reenforce uniqueness of attached light sources as in ye olden days
  src/main/java/net/rptools/maptool/model/AttachedLightSource.java
  src/main/java/net/rptools/maptool/model/Token.java
Labels: bug

#4375 Add missing tooltip for cover VBL
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#4370 Fix grid size labels
  src/main/java/net/rptools/maptool/client/tool/gridtool/AdjustGridControlPanelView.form
  src/main/java/net/rptools/maptool/client/ui/AppMenuBar.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/mappropertiesdialog/MapPropertiesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.form
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/i18n_cs.properties
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: bug

#4381 Use delimiters literally in macro functions
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/functions/ChatFunction.java
  src/main/java/net/rptools/maptool/client/functions/ExecFunction.java
  src/main/java/net/rptools/maptool/client/functions/FogOfWarFunctions.java
  src/main/java/net/rptools/maptool/client/functions/InputFunction.java
  src/main/java/net/rptools/maptool/client/functions/JSONMacroFunctionsOld.java
  src/main/java/net/rptools/maptool/client/functions/MacroLinkFunction.java
  src/main/java/net/rptools/maptool/client/functions/TokenSelectionFunctions.java
  src/main/java/net/rptools/maptool/client/functions/json/JsonArrayFunctions.java
  src/main/java/net/rptools/maptool/client/functions/json/JsonObjectFunctions.java
  src/main/java/net/rptools/maptool/util/StringUtil.java
  src/test/java/net/rptools/maptool/client/functions/json/JSONMacroFunctions.java
Labels: bug

#4385 Replace home-grown uberJar task with shadowJar plugin
  .github/workflows/publish.yml
  build.gradle
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/model/Asset.java
  src/main/java/net/rptools/maptool/server/ServerMessageHandler.java
Labels: bug

#4392 Fix handling of assert failures in event handlers
  src/main/java/net/rptools/maptool/client/functions/exceptions/AssertFunctionException.java
  src/main/java/net/rptools/maptool/util/EventMacroUtil.java
Labels: bug

#4393 Use the term "NPCs" in the Map Explorer window
  src/main/java/net/rptools/maptool/client/ui/tokenpanel/TokenPanelTreeModel.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#4401 Replace configSentryRelease task with processResources configuration
  .gitignore
  build.gradle
Labels: refactor

#4400 Avoid use of convention properties
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: refactor

#4404 Make ownership checks consistent between All Players and explicit assignment
  src/main/java/net/rptools/maptool/client/AppUtil.java
  src/main/java/net/rptools/maptool/client/functions/FindTokenFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenPropertyFunctions.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/model/library/token/LibraryToken.java
  src/main/java/net/rptools/maptool/util/EventMacroUtil.java
Labels: bug

#4424 Merge 1.14 back into develop
  build.gradle
  src/main/java/net/rptools/maptool/client/AppUtil.java
Labels: ignore-for-release-note

#4428 Upgrade to javafx 21
  build.gradle
Labels: feature

#4411 add nightly github action
  .github/workflows/nightly-publish.yml
Labels: feature

#4471 Upgrade PDF libraries
  build.gradle
  src/main/java/net/rptools/maptool/util/ExtractImagesFromPDF.java
Labels: dependencies

#4483 Add dependencies calc action
  .github/workflows/dependencies.yml
Labels: code-maintenance
