Repository RPTools/maptool, pull requests merged in 2023-04, with the labels that each got.

#3888 Update release.yml for auto building of release notes
  .github/release.yml
Labels: code-maintenance

#3935 Add CI to Merge Queue
  .github/workflows/verify-build.yml
Labels: repo-admin

#3940 Revert to FlatLaf 2.1 due to bug and incomplete upgrade from dependabot
  build.gradle
Labels: bug, ignore-for-release-note

#3944 Upgrade to FlatLaf version 3.1
  build.gradle
  src/main/java/net/rptools/maptool/client/ui/tokenpanel/TokenPanelTreeCellRenderer.java
Labels: feature

#3945 Upgrade JavaFX to version 20
  build.gradle
Labels: feature

#3946 Added dependancy upgrade section to release note
  .github/release.yml
Labels: feature

#3941 creates function setZoomLock(0/1) - fr#3438
  src/main/java/net/rptools/maptool/client/functions/ZoomFunctions.java
Labels: feature

#3951 functions- getMoveLock() - setMoveLock(0/1)
  src/main/java/net/rptools/maptool/client/functions/ServerFunctions.java
Labels: feature

#3953 Refactor ZoneView to keep lighting consistent
  src/main/java/net/rptools/maptool/client/ui/zone/IlluminationModel.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
Labels: ignore-for-release-note

#3947 Update actions in GitHub build
  .github/workflows/publish.yml
  .github/workflows/verify-build.yml
Labels: build-configuration

#3966 Allow mapped integers to be mapped back to integral BigDecimals (merge to develop)
  src/main/java/net/rptools/maptool/client/functions/ExecFunction.java
  src/main/java/net/rptools/maptool/server/Mapper.java
Labels: ignore-for-release-note

#3894 Show player loading status
  src/main/java/net/rptools/maptool/client/ClientMessageHandler.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/client/events/PlayerStatusChanged.java
  src/main/java/net/rptools/maptool/client/events/ZoneLoaded.java
  src/main/java/net/rptools/maptool/client/events/ZoneLoading.java
  src/main/java/net/rptools/maptool/client/swing/PlayersLoadingStatusBar.java
  src/main/java/net/rptools/maptool/client/ui/MapToolFrame.java
  src/main/java/net/rptools/maptool/client/ui/connections/ClientConnectionPanel.java
  src/main/java/net/rptools/maptool/client/ui/connections/PlayerListCellRenderer.java
  src/main/java/net/rptools/maptool/client/ui/theme/Icons.java
  src/main/java/net/rptools/maptool/client/ui/theme/RessourceManager.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java
  src/main/java/net/rptools/maptool/model/player/Player.java
  src/main/java/net/rptools/maptool/model/player/PlayerZoneListener.java
  src/main/java/net/rptools/maptool/server/MapToolServer.java
  src/main/java/net/rptools/maptool/server/ServerCommand.java
  src/main/java/net/rptools/maptool/server/ServerMessageHandler.java
  src/main/proto/data_transfer_objects.proto
  src/main/proto/message.proto
  src/main/proto/message_types.proto
  src/main/resources/net/rptools/maptool/client/image/loading.png
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#4000 Merge Dicelib code into MapTool Repo
  build.gradle
  settings.gradle
  src/main/java/net/rptools/dicelib/expression/ExpressionParser.java
  src/main/java/net/rptools/dicelib/expression/Result.java
  src/main/java/net/rptools/dicelib/expression/RunData.java
  src/main/java/net/rptools/dicelib/expression/function/ArsMagicaStress.java
  src/main/java/net/rptools/dicelib/expression/function/CountSuccessDice.java
  src/main/java/net/rptools/dicelib/expression/function/DiceHelper.java
  src/main/java/net/rptools/dicelib/expression/function/DropHighestRoll.java
  src/main/java/net/rptools/dicelib/expression/function/DropRoll.java
  src/main/java/net/rptools/dicelib/expression/function/ExplodeDice.java
  src/main/java/net/rptools/dicelib/expression/function/ExplodingSuccessDice.java
  src/main/java/net/rptools/dicelib/expression/function/FudgeRoll.java
  src/main/java/net/rptools/dicelib/expression/function/HeroKillingRoll.java
  src/main/java/net/rptools/dicelib/expression/function/HeroRoll.java
  src/main/java/net/rptools/dicelib/expression/function/If.java
  src/main/java/net/rptools/dicelib/expression/function/KeepLowestRoll.java
  src/main/java/net/rptools/dicelib/expression/function/KeepRoll.java
  src/main/java/net/rptools/dicelib/expression/function/OpenTestDice.java
  src/main/java/net/rptools/dicelib/expression/function/RerollDice.java
  src/main/java/net/rptools/dicelib/expression/function/RerollDiceOnce.java
  src/main/java/net/rptools/dicelib/expression/function/Roll.java
  src/main/java/net/rptools/dicelib/expression/function/RollWithBounds.java
  src/main/java/net/rptools/dicelib/expression/function/ShadowRun4Dice.java
  src/main/java/net/rptools/dicelib/expression/function/ShadowRun4ExplodeDice.java
  src/main/java/net/rptools/dicelib/expression/function/ShadowRun5Dice.java
  src/main/java/net/rptools/dicelib/expression/function/ShadowRun5ExplodeDice.java
  src/main/java/net/rptools/dicelib/expression/function/UbiquityRoll.java
  src/main/java/net/rptools/maptool/client/MapToolExpressionParser.java
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/OptionInfo.java
  src/main/java/net/rptools/maptool/client/functions/JSONMacroFunctionsOld.java
  src/main/java/net/rptools/maptool/client/functions/json/JSONMacroFunctions.java
  src/main/java/net/rptools/maptool/model/LookupTable.java
  src/test/java/net/rptools/dicelib/expression/ExpressionParserTest.java
  src/test/java/net/rptools/dicelib/expression/ExpressionParserWithMockRollsTest.java
  src/test/java/net/rptools/dicelib/expression/RunDataMockForTesting.java
  src/test/java/net/rptools/dicelib/expression/RunDataTest.java
  src/test/java/net/rptools/dicelib/expression/function/DiceHelperTest.java
  src/test/java/net/rptools/dicelib/expression/function/DropRollTest.java
  src/test/java/net/rptools/dicelib/expression/function/RollTest.java
  src/test/java/net/rptools/maptool/client/MapToolLineParserTest.java
  src/test/java/net/rptools/maptool/client/functions/GetRolledTest.java
Labels: build-configuration

#4005 Fix junit test
  src/test/java/net/rptools/maptool/client/functions/GetRolledTest.java
Labels: bug
