Repository RPTools/maptool, pull requests merged in 2023-06, with the labels that each got.

#4097 Fix for NPE on image list when adding bars
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialogView.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenBarController.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesManagementPanelView.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.java
Labels: bug

#4115 Merge 1.13.1 into develop
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialogView.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenBarController.java
  src/main/java/net/rptools/maptool/client/ui/theme/RessourceManager.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/model/drawing/Drawable.java
  src/main/java/net/rptools/maptool/model/drawing/LineTemplate.java
Labels: ignore-for-release-note

#4125 Update build to use 20.0.1 for packaging
  build.gradle
Labels: build-configuration

#4146 Fix missing statsheet css values
  src/main/java/net/rptools/maptool/model/library/builtin/themecss/ThemeCssContext.java
Labels: bug

#4153 Check trusted flag against BigDecimal.ZERO instead of casting to int
  src/main/java/net/rptools/maptool/client/functions/MacroJavaScriptBridge.java
Labels: bug

#4157 Reimplement the add-on dialog so that it follows the selected MT theme.
  build.gradle
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/AppConstants.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/ui/JLabelHyperLinkListener.java
  src/main/java/net/rptools/maptool/client/ui/ViewAssetDialog.java
  src/main/java/net/rptools/maptool/client/ui/addon/AddOnLibrariesDialogOld.java
  src/main/java/net/rptools/maptool/client/ui/addon/AddOnLibrariesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/addon/AddOnLibrariesDialogView.java
  src/main/java/net/rptools/maptool/client/ui/addon/AddOnLibrariesTableModel.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#4177 Clear Legacy Statsheet when moving between tokens
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
Labels: bug

#4156 Add buttons to the add-on dialog to easily copy MT Theme and MT Stat Sheet Theme CSS to the clipboard
  src/main/java/net/rptools/maptool/client/AppConstants.java
  src/main/java/net/rptools/maptool/client/ui/addon/AddOnLibrariesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/addon/AddOnLibrariesDialogView.java
  src/main/java/net/rptools/maptool/model/library/builtin/MapToolBuiltInLibrary.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#4167 Feature addon metadata
  src/main/java/net/rptools/maptool/model/library/addon/AddOnLibraryImporter.java
Labels: feature

#4173 Themed CSS updates
  src/main/java/net/rptools/maptool/model/library/builtin/themecss/ThemeCssContext.java
  src/main/java/net/rptools/maptool/model/library/builtin/themecss/ThemeHeader.java
  src/main/resources/net/rptools/maptool/library/builtin/mt-stat-sheet-css.hbs
  src/main/resources/net/rptools/maptool/library/builtin/mt-theme-css.hbs
Labels: feature
