Repository RPTools/maptool, pull requests merged in 2024-10, with the labels that each got.

#4964 Fix NPE on partially initialized square grids
  src/main/java/net/rptools/maptool/client/functions/MapFunctions.java
  src/main/java/net/rptools/maptool/client/tool/DefaultTool.java
  src/main/java/net/rptools/maptool/client/tool/FacingTool.java
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
  src/main/java/net/rptools/maptool/client/ui/mappropertiesdialog/MapPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/theme/Images.java
  src/main/java/net/rptools/maptool/client/ui/theme/RessourceManager.java
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/GridFactory.java
  src/main/java/net/rptools/maptool/model/GridlessGrid.java
  src/main/java/net/rptools/maptool/model/HexGrid.java
  src/main/java/net/rptools/maptool/model/HexGridHorizontal.java
  src/main/java/net/rptools/maptool/model/HexGridVertical.java
  src/main/java/net/rptools/maptool/model/IsometricGrid.java
  src/main/java/net/rptools/maptool/model/SquareGrid.java
  src/main/java/net/rptools/maptool/model/ZoneFactory.java
  src/main/java/net/rptools/maptool/util/TokenUtil.java
  src/main/resources/net/rptools/maptool/client/image/grid-square-orage.png
  src/main/resources/net/rptools/maptool/client/image/grid-square-red.png
  src/test/java/net/rptools/maptool/model/GridlessGridTest.java
  src/test/java/net/rptools/maptool/model/HexGridHorizontalTest.java
  src/test/java/net/rptools/maptool/model/HexGridVerticalTest.java
  src/test/java/net/rptools/maptool/model/IsometricGridTest.java
  src/test/java/net/rptools/maptool/model/SquareGridTest.java
  src/test/resources/net/rptools/maptool/model/GridlessGrid.nearestFacing.csv
  src/test/resources/net/rptools/maptool/model/GridlessGrid.nextFacing.csv
  src/test/resources/net/rptools/maptool/model/HexGridHorizontal.nearestFacing.csv
  src/test/resources/net/rptools/maptool/model/HexGridHorizontal.nextFacing.csv
  src/test/resources/net/rptools/maptool/model/HexGridVertical.nearestFacing.csv
  src/test/resources/net/rptools/maptool/model/HexGridVertical.nextFacing.csv
  src/test/resources/net/rptools/maptool/model/IsometricGrid.nearestFacing.csv
  src/test/resources/net/rptools/maptool/model/IsometricGrid.nextFacing.csv
  src/test/resources/net/rptools/maptool/model/SquareGrid.nearestFacing.csv
  src/test/resources/net/rptools/maptool/model/SquareGrid.nextFacing.csv
Labels: bug

#4963 Fixed ButtonGroup drag event drop checks #4959
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttongroups/ButtonGroup.java
Labels: bug

#4955 Do not modify token facing when calculating light and vision
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/IsometricGrid.java
  src/main/java/net/rptools/maptool/model/Token.java
Labels: bug

#4968 Fixed State/Bar images resizing on rotated tokens
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
Labels: bug

#4973 Fix light offset for beams to measure counterclockwise as for cones
  src/main/java/net/rptools/maptool/model/Grid.java
Labels: bug

#4983 Do not show local player in Connections window or status panel
  src/main/java/net/rptools/maptool/client/MapToolClient.java
  src/main/java/net/rptools/maptool/client/events/PlayerConnected.java
  src/main/java/net/rptools/maptool/client/swing/PlayersLoadingStatusBar.java
  src/main/java/net/rptools/maptool/client/ui/connections/ClientConnectionPanel.java
Labels: feature

#4979 Fix hex light construction
  src/main/java/net/rptools/maptool/model/Grid.java
Labels: bug

#4993 Fix new compile warning
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
Labels: code-maintenance

#4981 Decompose `Grid.getShapedArea()` so we can reuse logic between grids
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/IsometricGrid.java
  src/main/java/net/rptools/maptool/model/Zone.java
Labels: bug, code-maintenance

#4982 Do not disclose GM maps to players in status UI
  src/main/java/net/rptools/maptool/client/swing/PlayersLoadingStatusBar.java
  src/main/java/net/rptools/maptool/client/ui/connections/PlayerListCellRenderer.java
Labels: bug

#5003 Revert "Provide functionality for add-on development"
  build.gradle
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/ui/addon/AddOnLibrariesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/addon/AddOnLibrariesDialogView.java
  src/main/java/net/rptools/maptool/client/ui/addon/AddOnLibrariesTableModel.java
  src/main/java/net/rptools/maptool/client/ui/addon/CreateNewAddonDialog.form
  src/main/java/net/rptools/maptool/client/ui/addon/CreateNewAddonDialog.java
  src/main/java/net/rptools/maptool/client/ui/addon/ExternalAddOnImportCellEditor.java
  src/main/java/net/rptools/maptool/client/ui/addon/ExternalAddOnLibrariesTableModel.java
  src/main/java/net/rptools/maptool/client/ui/addon/creator/MTLibCreator.java
  src/main/java/net/rptools/maptool/client/ui/addon/creator/NewAddOn.java
  src/main/java/net/rptools/maptool/client/ui/addon/creator/NewAddOnBuilder.java
  src/main/java/net/rptools/maptool/client/ui/addon/creator/NewAddOnCreator.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/java/net/rptools/maptool/model/library/ExternalAddonsUpdateEvent.java
  src/main/java/net/rptools/maptool/model/library/LibraryManager.java
  src/main/java/net/rptools/maptool/model/library/addon/AddOnLibrary.java
  src/main/java/net/rptools/maptool/model/library/addon/AddOnLibraryImporter.java
  src/main/java/net/rptools/maptool/model/library/addon/AddOnLibraryManager.java
  src/main/java/net/rptools/maptool/model/library/addon/ExternalAddOnLibraryManager.java
  src/main/java/net/rptools/maptool/model/library/addon/ExternalLibraryInfo.java
  src/main/java/net/rptools/maptool/util/FileUtil.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/i18n_cs.properties
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_en.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_AU.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_GB.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_si.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: ignore-for-release-note

#5019 Fix various issues with transfering map topology to and from token topology
  src/main/java/net/rptools/maptool/client/ClientMessageHandler.java
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/client/functions/Topology_Functions.java
  src/main/java/net/rptools/maptool/client/tool/drawing/CrossTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DiamondTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowDiamondTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowOvalTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowRectangleTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/OvalTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/PolygonTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RectangleTopologyTool.java
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/TokenVBL.java
  src/main/java/net/rptools/maptool/client/utilities/DungeonDraftImporter.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/server/ServerCommand.java
  src/main/java/net/rptools/maptool/server/ServerMessageHandler.java
  src/main/proto/message.proto
  src/main/proto/message_types.proto
Labels: bug
