Repository RPTools/maptool, pull requests merged in 2024-01, with the labels that each got.

#4596 Alternate Encoding Handling for Addon Content
  src/main/java/net/rptools/maptool/model/Asset.java
Labels: bug

#4605 MetaMacro function fix fix
  src/main/java/net/rptools/maptool/client/functions/MacroFunctions.java
Labels: bug

#4532 Added new chat function _chat_ that allows running slash commands in macros.
  src/main/java/net/rptools/maptool/client/functions/ChatFunction.java
  src/main/java/net/rptools/maptool/client/macro/MacroManager.java
  src/main/java/net/rptools/maptool/client/macro/impl/AboutMacro.java
Labels: feature

#4608 Updated light help text
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: refactor

#4616 Remove leftover bits from the campaign export removal
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/resources/net/rptools/maptool/client/ui/forms/campaignExportDialog.xml
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/i18n_ach.properties
  src/main/resources/net/rptools/maptool/language/i18n_cs.properties
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_en.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_au.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_gb.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: refactor

#4630 Improve last path exposure with better unions
  src/main/java/net/rptools/lib/GeometryUtil.java
  src/main/java/net/rptools/maptool/client/ui/zone/FogUtil.java
Labels: refactor

#4629 Updated FunctionUtil to handle `lib://` assets via AssetResolver
  src/main/java/net/rptools/maptool/client/functions/InputFunction.java
  src/main/java/net/rptools/maptool/client/functions/MapFunctions.java
  src/main/java/net/rptools/maptool/util/FunctionUtil.java
Labels: bug

#4635 UI text - Campaign Properties Dialogue
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesManagementPanelView.form
  src/main/resources/net/rptools/maptool/client/ui/forms/campaignPropertiesDialog.xml
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/i18n_cs.properties
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_en.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_au.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_gb.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
  src/test/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialogTest.java
Labels: refactor

#4642 Improve performance of the visibility sweep
  src/main/java/net/rptools/lib/CodeTimer.java
  src/main/java/net/rptools/maptool/client/ui/zone/FogUtil.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/AreaMeta.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/EndpointSet.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/VisibilityProblem.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/VisibilitySweepEndpoint.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/VisionBlockingAccumulator.java
Labels: performance

#4644 Updated dice systems to handle exploding dice limits
  src/main/java/net/rptools/dicelib/expression/ExpressionParser.java
  src/main/java/net/rptools/dicelib/expression/function/DiceHelper.java
  src/main/java/net/rptools/dicelib/expression/function/ExplodeDice.java
  src/main/java/net/rptools/dicelib/expression/function/ExplodingSuccessDice.java
  src/main/java/net/rptools/dicelib/expression/function/OpenTestDice.java
  src/test/java/net/rptools/dicelib/expression/function/DiceHelperTest.java
Labels: feature

#4652 Added a utility class for generating a report on i18n strings.
  src/main/java/net/rptools/maptool/language/I18N.java
  src/main/java/net/rptools/maptool/language/I18nTools.java
Labels: refactor, translations

#4653 Reworked Token Type/Properties Editor tab
  src/main/java/net/rptools/maptool/client/swing/AbeillePanel.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesManagementPanel.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesManagementPanelView.form
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesManagementPanelView.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesTableModel.java
  src/main/java/net/rptools/maptool/client/ui/exportdialog/ExportDialog.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature
