Repository RPTools/maptool, pull requests merged in 2024-07, with the labels that each got.

#4858 Remove property files with same name differing case to let crowdin to send only one set
  src/main/resources/net/rptools/maptool/language/i18n_en_AU.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_GB.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_au.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_gb.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt_BR.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt_br.properties
Labels: build-configuration

#4861 BoardTool upgraded to control map image scale
  src/main/java/net/rptools/maptool/client/tool/boardtool/AdjustBoardControlPanelView.form
  src/main/java/net/rptools/maptool/client/tool/boardtool/AdjustBoardControlPanelView.java
  src/main/java/net/rptools/maptool/client/tool/boardtool/BoardTool.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#4863 Apply changes made to token properties in the campaign settings when pressing "Ok"
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesManagementPanel.java
Labels: bug

#4864 Keep selected token property in view when moving it up or down a big property table
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesManagementPanel.java
Labels: bug

#4865 Call finalizeCellEditing() before switching tokenTypes to make sure t…
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesManagementPanel.java
Labels: bug
