Repository RPTools/maptool, pull requests merged in 2024-05, with the labels that each got.

#4763 Give DrawnElement a copy constructor
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/model/drawing/AbstractDrawing.java
  src/main/java/net/rptools/maptool/model/drawing/AbstractTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/BlastTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/BurstTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/ConeTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/Cross.java
  src/main/java/net/rptools/maptool/model/drawing/Drawable.java
  src/main/java/net/rptools/maptool/model/drawing/DrawablesGroup.java
  src/main/java/net/rptools/maptool/model/drawing/DrawnElement.java
  src/main/java/net/rptools/maptool/model/drawing/DrawnLabel.java
  src/main/java/net/rptools/maptool/model/drawing/LineCellTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/LineSegment.java
  src/main/java/net/rptools/maptool/model/drawing/LineTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/Oval.java
  src/main/java/net/rptools/maptool/model/drawing/RadiusCellTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/RadiusTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/Rectangle.java
  src/main/java/net/rptools/maptool/model/drawing/ShapeDrawable.java
  src/main/java/net/rptools/maptool/model/drawing/WallTemplate.java
Labels: bug

#4771 Refactor client-side and server-side state, split player database responsibilities, and enforce better lifecylce for servers and clients
  clientserver/src/main/java/net/rptools/clientserver/simple/Handshake.java
  clientserver/src/main/java/net/rptools/clientserver/simple/connection/SocketConnection.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/AbstractServer.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/SocketServer.java
  src/main/java/net/rptools/clientserver/ConnectionFactory.java
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/ClientMessageHandler.java
  src/main/java/net/rptools/maptool/client/IMapToolConnection.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/MapToolClient.java
  src/main/java/net/rptools/maptool/client/MapToolConnection.java
  src/main/java/net/rptools/maptool/client/MapToolVariableResolver.java
  src/main/java/net/rptools/maptool/client/NilMapToolConnection.java
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/client/ServerDisconnectHandler.java
  src/main/java/net/rptools/maptool/client/events/ServerDisconnected.java
  src/main/java/net/rptools/maptool/client/functions/MacroLinkFunction.java
  src/main/java/net/rptools/maptool/client/functions/PlayerFunctions.java
  src/main/java/net/rptools/maptool/client/functions/ServerFunctions.java
  src/main/java/net/rptools/maptool/client/macro/impl/WhisperMacro.java
  src/main/java/net/rptools/maptool/client/macro/impl/WhisperReplyMacro.java
  src/main/java/net/rptools/maptool/client/swing/PlayersLoadingStatusBar.java
  src/main/java/net/rptools/maptool/client/tool/AI_Tool.java
  src/main/java/net/rptools/maptool/client/tool/AI_UseVblTool.java
  src/main/java/net/rptools/maptool/client/ui/MapToolFrame.java
  src/main/java/net/rptools/maptool/client/ui/connectioninfodialog/ConnectionInfoDialog.java
  src/main/java/net/rptools/maptool/client/ui/connections/ClientConnectionPanel.java
  src/main/java/net/rptools/maptool/client/ui/players/PlayerDatabaseDialogController.java
  src/main/java/net/rptools/maptool/client/ui/players/PlayerDatabaseEditController.java
  src/main/java/net/rptools/maptool/model/AssetLoader.java
  src/main/java/net/rptools/maptool/model/player/DefaultPlayerDatabase.java
  src/main/java/net/rptools/maptool/model/player/LocalPlayer.java
  src/main/java/net/rptools/maptool/model/player/LocalPlayerDatabase.java
  src/main/java/net/rptools/maptool/model/player/PasswordFilePlayerDatabase.java
  src/main/java/net/rptools/maptool/model/player/PersonalServerPlayerDatabase.java
  src/main/java/net/rptools/maptool/model/player/PlayerDatabase.java
  src/main/java/net/rptools/maptool/model/player/PlayerDatabaseFactory.java
  src/main/java/net/rptools/maptool/model/player/Players.java
  src/main/java/net/rptools/maptool/model/player/ServerSidePlayerDatabase.java
  src/main/java/net/rptools/maptool/server/ClientHandshake.java
  src/main/java/net/rptools/maptool/server/IMapToolServer.java
  src/main/java/net/rptools/maptool/server/MapToolServer.java
  src/main/java/net/rptools/maptool/server/MapToolServerConnection.java
  src/main/java/net/rptools/maptool/server/PersonalServer.java
  src/main/java/net/rptools/maptool/server/ServerConfig.java
  src/main/java/net/rptools/maptool/server/ServerHandshake.java
  src/main/java/net/rptools/maptool/server/ServerMessageHandler.java
  src/main/java/net/rptools/maptool/server/ServerPolicy.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/test/java/net/rptools/lib/GeometryUtilTest.java
  src/test/java/net/rptools/maptool/client/MapToolLineParserTest.java
  src/test/java/net/rptools/maptool/model/TokenPropertiesTest.java
Labels: bug

#4774 Go back to calling MapTool.setCampaign()
  src/main/java/net/rptools/maptool/client/ClientMessageHandler.java
Labels: bug

#4773 Update topology toolbar tooltip to include movement blocking
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
  src/main/java/net/rptools/maptool/client/tool/StampTool.java
  src/main/java/net/rptools/maptool/client/tool/boardtool/BoardTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/CrossTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DiamondTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DrawnTextTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowDiamondTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowOvalTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowRectangleTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/LineTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/OvalTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/OvalTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RectangleTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/gridtool/GridTool.java
  src/main/java/net/rptools/maptool/model/drawing/DrawnLabel.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#4780 Persist new public keys in the player database when using Easy Connect
  src/main/java/net/rptools/maptool/server/ServerHandshake.java
Labels: bug

#4777 More client lifecycle improvements
  clientserver/src/main/java/net/rptools/clientserver/simple/Handshake.java
  clientserver/src/main/java/net/rptools/clientserver/simple/HandshakeObserver.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/AbstractServer.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/HandshakeProvider.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/SocketServer.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/WebRTCServer.java
  src/main/java/net/rptools/clientserver/ConnectionFactory.java
  src/main/java/net/rptools/maptool/client/MapToolClient.java
  src/main/java/net/rptools/maptool/client/MapToolConnection.java
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/client/ui/players/PlayerDatabaseDialogController.java
  src/main/java/net/rptools/maptool/model/player/PasswordFilePlayerDatabase.java
  src/main/java/net/rptools/maptool/model/player/PersistedPlayerDatabase.java
  src/main/java/net/rptools/maptool/model/player/PlayerDBPropertyChange.java
  src/main/java/net/rptools/maptool/model/player/Players.java
  src/main/java/net/rptools/maptool/server/ClientHandshake.java
  src/main/java/net/rptools/maptool/server/MapToolServerConnection.java
  src/main/java/net/rptools/maptool/server/ServerHandshake.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#4787 Further improvements to server starts
  clientserver/build.gradle
  clientserver/src/main/java/net/rptools/clientserver/simple/Handshake.java
  clientserver/src/main/java/net/rptools/clientserver/simple/connection/AbstractConnection.java
  clientserver/src/main/java/net/rptools/clientserver/simple/connection/DirectConnection.java
  clientserver/src/main/java/net/rptools/clientserver/simple/connection/SocketConnection.java
  clientserver/src/main/java/net/rptools/clientserver/simple/connection/WebRTCConnection.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/AbstractServer.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/NilServer.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/Router.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/Server.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/ServerObserver.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/SocketServer.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/WebRTCServer.java
  clientserver/src/test/java/net/rptools/clientserver/simple/server/RouterTest.java
  src/main/java/net/rptools/clientserver/ConnectionFactory.java
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/ClientMessageHandler.java
  src/main/java/net/rptools/maptool/client/IMapToolConnection.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/MapToolClient.java
  src/main/java/net/rptools/maptool/client/MapToolConnection.java
  src/main/java/net/rptools/maptool/client/NilMapToolConnection.java
  src/main/java/net/rptools/maptool/client/ui/MapToolFrame.java
  src/main/java/net/rptools/maptool/client/ui/connectioninfodialog/ConnectionInfoDialog.java
  src/main/java/net/rptools/maptool/model/player/PersonalServerPlayerDatabase.java
  src/main/java/net/rptools/maptool/model/player/PlayerDatabaseFactory.java
  src/main/java/net/rptools/maptool/server/ClientHandshake.java
  src/main/java/net/rptools/maptool/server/Handshake.java
  src/main/java/net/rptools/maptool/server/MapToolServer.java
  src/main/java/net/rptools/maptool/server/MapToolServerConnection.java
  src/main/java/net/rptools/maptool/server/PersonalServer.java
  src/main/java/net/rptools/maptool/server/ServerHandshake.java
  src/main/java/net/rptools/maptool/server/ServerMessageHandler.java
  src/main/java/net/rptools/maptool/util/cipher/CipherUtil.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: refactor, performance

#4791 Replace token IDs on imported maps
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/util/PersistenceUtil.java
Labels: bug

#4802 Do not run the InfoTextSwingWorker on the EDT thread
  src/main/java/net/rptools/maptool/client/ui/SysInfoDialog.java
  src/main/java/net/rptools/maptool/client/walker/AbstractZoneWalker.java
  src/main/java/net/rptools/maptool/client/walker/ZoneWalker.java
Labels: bug

#4792 Update crowdin.yml to extend translation file suffix with locale
  crowdin.yml
Labels: feature

#4800 Add workaround for drag and drop between frames
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLWebViewManager.java
Labels: bug

#4803 Magnify light source radius rather than shape
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/VisionOverlayRenderer.java
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/Light.java
  src/main/java/net/rptools/maptool/model/LightSource.java
Labels: bug

#4804 Check windows based on hidden status, not showing
  src/main/java/net/rptools/maptool/client/AppActions.java
Labels: bug

#4806 Even the local client needs the player list synced
  src/main/java/net/rptools/maptool/server/MapToolServer.java
Labels: bug

#4805 Add read timeouts to server sockets
  clientserver/src/main/java/net/rptools/clientserver/simple/connection/SocketConnection.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/SocketServer.java
Labels: bug

#4807 Fix for missing translation keys
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelTreeModel.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#4812 Swap hex grid icons in Rod's theme
  src/main/resources/net/rptools/maptool/client/icons/rod_takehara/gridHorizontalHex.svg
  src/main/resources/net/rptools/maptool/client/icons/rod_takehara/gridVerticalHex.svg
Labels: bug

#4809 Constrain zoom levels
  src/main/java/net/rptools/maptool/client/swing/ZoomStatusBar.java
  src/main/java/net/rptools/maptool/client/ui/Scale.java
  src/main/java/net/rptools/maptool/client/ui/adjustgrid/AdjustGridPanel.java
  src/main/java/net/rptools/maptool/client/ui/adjustgrid/AdvancedAdjustGridPanel.java
Labels: bug

#4810 Fix onChangeSelection and related events for inactive tabbed frames
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLFrame.java
Labels: bug
