Repository RPTools/maptool, pull requests merged in 2024-09, with the labels that each got.

#4884 Fix themes, default property sets not being installed correctly
  src/main/java/net/rptools/maptool/client/AppSetup.java
Labels: bug

#4887 hasLightSource & Campaign Panel drag-drop bug fix
  src/main/java/net/rptools/maptool/client/functions/TokenLightFunctions.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttongroups/ButtonGroup.java
Labels: bug

#4896 Return JSON on rest failure to mtscript instead of exception
  src/main/java/net/rptools/maptool/client/functions/RESTfulFunctions.java
Labels: feature

#4888 Modify ButtonGroup drag to check for no change
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttongroups/ButtonGroup.java
Labels: bug

#4904 Reduce number of interfaces scanned for UPnP gateways
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/util/UPnPUtil.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug, performance

#4908 Change version of copy issue label to pr job
  .github/workflows/copy-label-to-pr.yml
Labels: ignore-for-release-note

#4942 Fix darkness in GM views
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/DarknessRenderer.java
Labels: bug

#4943 Fix darkness in GM views (reapply #4942)
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/DarknessRenderer.java
Labels: bug

#4911 revert to intel runner for mac os (Reapply #4893)
  .github/workflows/publish.yml
  .github/workflows/verify-build.yml
Labels: ignore-for-release-note

#4910 small fix for installUsingReflection() (Reapply #4884)
  src/main/java/net/rptools/maptool/client/AppSetup.java
Labels: ignore-for-release-note

#4909 Rename hex grid icon files in Rod Takehara theme (reapply #4812)
  src/main/resources/net/rptools/maptool/client/icons/rod_takehara/gridHorizontalHex.svg
  src/main/resources/net/rptools/maptool/client/icons/rod_takehara/gridVerticalHex.svg
Labels: ignore-for-release-note

#4922 hastLightSource will return expected results like 1.14.3 (reapply #4887)
  src/main/java/net/rptools/maptool/client/functions/TokenLightFunctions.java
Labels: ignore-for-release-note

#4940 Restrict each drawable light to its lumens level
  src/main/java/net/rptools/maptool/client/ui/zone/Illumination.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/model/zones/ZoneLightingChanged.java
Labels: feature

#4952 Fix translation issues on 1.15
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#4953 Port missing 1.14 commits to develop
  .github/workflows/publish.yml
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLWebViewManager.java
Labels: bug

#4948 Fix translation of "Clear GM Auras Only" menu item
  src/main/java/net/rptools/maptool/client/ui/AbstractTokenPopupMenu.java
Labels: bug

#4949 Add clear lights menu items only once
  src/main/java/net/rptools/maptool/client/ui/AbstractTokenPopupMenu.java
Labels: bug
