Repository RPTools/maptool, pull requests merged in 2024-02, with the labels that each got.

#4668 Ensure GeometryUtil.toJts() returns valid geometry
  src/main/java/net/rptools/lib/GeometryUtil.java
  src/main/java/net/rptools/maptool/client/walker/astar/AbstractAStarWalker.java
  src/main/java/net/rptools/maptool/server/Mapper.java
  src/test/java/net/rptools/lib/GeometryUtilTest.java
Labels: performance

#4662 Update Map and Token Labels to allow users to define how they look
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/swing/label/FlatImageLabel.java
  src/main/java/net/rptools/maptool/client/swing/label/FlatImageLabelFactory.java
  src/main/java/net/rptools/maptool/client/tool/texttool/EditLabelDialogView.form
  src/main/java/net/rptools/maptool/client/tool/texttool/EditLabelDialogView.java
  src/main/java/net/rptools/maptool/client/tool/texttool/TextTool.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/model/Label.java
  src/main/java/net/rptools/maptool/model/transform/campaign/LabelFontAndBGTransform.java
  src/main/java/net/rptools/maptool/util/PersistenceUtil.java
  src/main/proto/data_transfer_objects.proto
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#4685 Mark .form files as inputs to :instrumentForms task
  build.gradle
Labels: code-maintenance

#4696 Fix for #4695: library.getContents() returns empty JSON sometimes
  src/main/java/net/rptools/maptool/client/functions/LibraryFunctions.java
Labels: bug
