Repository RPTools/maptool, pull requests merged in 2024-04, with the labels that each got.

#4746 Automatically copy relevant issue labels to Pull Requests
  .github/workflows/copy-label-to-pr.yml
Labels: feature, build-configuration

#4745 Update to JavaFx 22
  build.gradle
Labels: feature

#4760 Update copy-label-to-pr.yml
  .github/workflows/copy-label-to-pr.yml
Labels: ignore-for-release-note

#4752 Fix rendering of line cell templates
  src/main/java/net/rptools/maptool/client/tool/drawing/LineCellTemplateTool.java
  src/main/java/net/rptools/maptool/model/CellPoint.java
  src/main/java/net/rptools/maptool/model/ZonePoint.java
  src/main/java/net/rptools/maptool/model/drawing/Drawable.java
  src/main/java/net/rptools/maptool/model/drawing/LineCellTemplate.java
  src/main/proto/drawing_dto.proto
Labels: bug

#4751 Move clientserver package into a new subproject
  build.gradle
  buildSrc/shared.gradle
  clientserver/build.gradle
  clientserver/src/main/java/net/rptools/clientserver/ActivityListener.java
  clientserver/src/main/java/net/rptools/clientserver/simple/DisconnectHandler.java
  clientserver/src/main/java/net/rptools/clientserver/simple/Handshake.java
  clientserver/src/main/java/net/rptools/clientserver/simple/HandshakeObserver.java
  clientserver/src/main/java/net/rptools/clientserver/simple/MessageHandler.java
  clientserver/src/main/java/net/rptools/clientserver/simple/connection/AbstractConnection.java
  clientserver/src/main/java/net/rptools/clientserver/simple/connection/Connection.java
  clientserver/src/main/java/net/rptools/clientserver/simple/connection/SocketConnection.java
  clientserver/src/main/java/net/rptools/clientserver/simple/connection/WebRTCConnection.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/AbstractServer.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/HandshakeProvider.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/Server.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/ServerObserver.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/SocketServer.java
  clientserver/src/main/java/net/rptools/clientserver/simple/server/WebRTCServer.java
  clientserver/src/main/java/net/rptools/clientserver/simple/webrtc/AnswerMessageDto.java
  clientserver/src/main/java/net/rptools/clientserver/simple/webrtc/CandidateMessageDto.java
  clientserver/src/main/java/net/rptools/clientserver/simple/webrtc/LoginMessageDto.java
  clientserver/src/main/java/net/rptools/clientserver/simple/webrtc/MessageDto.java
  clientserver/src/main/java/net/rptools/clientserver/simple/webrtc/OfferMessageDto.java
  settings.gradle
  src/main/java/net/rptools/clientserver/ConnectionFactory.java
  src/main/java/net/rptools/maptool/client/MapToolConnection.java
  src/main/java/net/rptools/maptool/server/ClientHandshake.java
  src/main/java/net/rptools/maptool/server/MapToolServerConnection.java
  src/main/java/net/rptools/maptool/server/ServerHandshake.java
Labels: code-maintenance
