Repository RPTools/maptool, pull requests merged in 2024-11, with the labels that each got.

#5027 Fix erase flag when DungeonDraftImporter adds topology to the zone
  src/main/java/net/rptools/maptool/client/utilities/DungeonDraftImporter.java
Labels: bug

#5011 Decompose drawing, expose, and topology tools
  src/main/java/net/rptools/maptool/client/functions/DrawingFunctions.java
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
  src/main/java/net/rptools/maptool/client/tool/StampTool.java
  src/main/java/net/rptools/maptool/client/tool/ToolHelper.java
  src/main/java/net/rptools/maptool/client/tool/Toolbox.java
  src/main/java/net/rptools/maptool/client/tool/drawing/AbstractDrawingLikeTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/AbstractDrawingTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/AbstractLineTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/AbstractTemplateTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/CrossStrategy.java
  src/main/java/net/rptools/maptool/client/tool/drawing/CrossTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DiamondExposeTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DiamondTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DiamondTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DrawingResult.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DrawingTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/ExposeTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/FreehandExposeTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/FreehandTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowDiamondTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowOvalTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/HollowRectangleTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/IsoRectangleStrategy.java
  src/main/java/net/rptools/maptool/client/tool/drawing/LineTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/Measurement.java
  src/main/java/net/rptools/maptool/client/tool/drawing/OvalExposeTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/OvalStrategy.java
  src/main/java/net/rptools/maptool/client/tool/drawing/OvalTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/OvalTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/PolyLineStrategy.java
  src/main/java/net/rptools/maptool/client/tool/drawing/PolyLineTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/PolygonExposeTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/PolygonTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/PolygonTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RadiusCellTemplateTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RadiusTemplateTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RectangleExposeTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RectangleStrategy.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RectangleTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/RectangleTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/Strategy.java
  src/main/java/net/rptools/maptool/client/tool/drawing/TopologyTool.java
  src/main/java/net/rptools/maptool/client/ui/AbstractTokenPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/ToolbarPanel.java
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelTreeCellRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/model/drawing/Cross.java
  src/main/java/net/rptools/maptool/model/drawing/Drawable.java
  src/main/java/net/rptools/maptool/model/drawing/LineSegment.java
  src/main/java/net/rptools/maptool/model/drawing/Oval.java
  src/main/java/net/rptools/maptool/model/drawing/Rectangle.java
  src/main/java/net/rptools/maptool/model/drawing/ShapeDrawable.java
  src/main/java/net/rptools/maptool/server/Mapper.java
  src/main/java/net/rptools/maptool/util/GraphicsUtil.java
  src/main/proto/drawing_dto.proto
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: refactor

#4906 Fix onFirstInit running every time when there is JS but no MTS
  src/main/java/net/rptools/maptool/model/library/addon/AddOnLibrary.java
Labels: bug

#5033 Fix map dragging state management in DefaultTool
  src/main/java/net/rptools/maptool/client/tool/DefaultTool.java
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
Labels: bug

#5049 Bump google-java-format version to 1.24.0
  buildSrc/shared.gradle
  src/main/java/net/rptools/dicelib/expression/function/advanced/AdvancedDiceRolls.java
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/TransferableHelper.java
  src/main/java/net/rptools/maptool/client/functions/ChatFunction.java
  src/main/java/net/rptools/maptool/client/functions/DataFunctions.java
  src/main/java/net/rptools/maptool/client/functions/LibraryFunctions.java
  src/main/java/net/rptools/maptool/client/functions/MacroLinkFunction.java
  src/main/java/net/rptools/maptool/client/functions/MapFunctions.java
  src/main/java/net/rptools/maptool/client/functions/PlayerFunctions.java
  src/main/java/net/rptools/maptool/client/functions/ServerFunctions.java
  src/main/java/net/rptools/maptool/client/functions/SlashCommands.java
  src/main/java/net/rptools/maptool/client/macro/MacroManager.java
  src/main/java/net/rptools/maptool/client/ui/AppMenuBar.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesManagementPanel.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesTableModel.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttons/MacroButton.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/LightsRenderer.java
  src/main/java/net/rptools/maptool/model/Asset.java
  src/main/java/net/rptools/maptool/model/drawing/ShapeDrawable.java
  src/main/java/net/rptools/maptool/model/gamedata/GameDataImporter.java
  src/main/java/net/rptools/maptool/model/gamedata/data/DataType.java
  src/main/java/net/rptools/maptool/model/gamedata/data/StringDataValue.java
  src/main/java/net/rptools/maptool/server/ServerMessageHandler.java
Labels: code-maintenance

#5051 #3414 Feature to lock an overlay
  src/main/java/net/rptools/maptool/client/functions/MacroDialogFunctions.java
  src/main/java/net/rptools/maptool/client/ui/AppMenuBar.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLFrameFactory.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLOverlayManager.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLOverlayPanel.java
  src/main/java/net/rptools/maptool/client/ui/sheet/stats/StatSheet.java
Labels: feature

#5055 Add landing maps to campaigns
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/ClientMessageHandler.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/client/ui/AppMenuBar.java
  src/main/java/net/rptools/maptool/model/Campaign.java
  src/main/java/net/rptools/maptool/server/ServerCommand.java
  src/main/java/net/rptools/maptool/server/ServerMessageHandler.java
  src/main/proto/data_transfer_objects.proto
  src/main/proto/message.proto
  src/main/proto/message_types.proto
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#5053 Add a start/stop lifecycle for ServerCommandClientImpl
  src/main/java/net/rptools/maptool/client/MapToolClient.java
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/server/MapToolServer.java
Labels: bug, code-maintenance

#5059 Bump copy-issue-labels to latest (1.3.0) - take 2
  .github/workflows/copy-label-to-pr.yml
Labels: code-maintenance

#5064 Add "Is landing map?" checkbox to map properties dialog
  src/main/java/net/rptools/maptool/client/ui/mappropertiesdialog/MapPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/mappropertiesdialog/MapPropertiesDialogView.form
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#5060 Remove max size for blast templates
  src/main/java/net/rptools/maptool/model/drawing/AbstractTemplate.java
  src/main/java/net/rptools/maptool/model/drawing/BlastTemplate.java
Labels: bug

#5067 Bring back unique light sources (no new macro functions)
  src/main/java/net/rptools/maptool/client/ServerCommandClientImpl.java
  src/main/java/net/rptools/maptool/client/functions/TokenLightFunctions.java
  src/main/java/net/rptools/maptool/client/ui/AbstractTokenPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.form
  src/main/java/net/rptools/maptool/client/ui/zone/LightSourceIconOverlay.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/client/utilities/DungeonDraftImporter.java
  src/main/java/net/rptools/maptool/model/AttachedLightSource.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/server/ServerCommand.java
  src/main/proto/data_transfer_objects.proto
Labels: feature
