Repository RPTools/maptool, pull requests merged in 2025-02, with the labels that each got.

#5148 Fix noded topology cache invalidation
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/model/Zone.java
Labels: bug

#5169 Drawing tools should always be available, even for players
  src/main/java/net/rptools/maptool/client/tool/drawing/DrawingTool.java
Labels: bug

#5176 Merge 1.16 into develop
  src/main/java/net/rptools/maptool/client/tool/drawing/DrawingTool.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneView.java
  src/main/java/net/rptools/maptool/model/AssetManager.java
  src/main/java/net/rptools/maptool/model/Zone.java
Labels: ignore-for-release-note

#5175 Default campaign props with metric values
  src/main/resources/net/rptools/maptool/model/campaignProps/metric Dungeons and Dragons 3e.mtprops
  src/main/resources/net/rptools/maptool/model/campaignProps/metric Dungeons and Dragons 4e.mtprops
  src/main/resources/net/rptools/maptool/model/campaignProps/metric Dungeons and Dragons 5e.mtprops
  src/main/resources/net/rptools/maptool/model/campaignProps/metric Lost Souls v2.mtprops
  src/main/resources/net/rptools/maptool/model/campaignProps/metric Path Finder 1e.mtprops
  src/main/resources/net/rptools/maptool/model/campaignProps/metric Path Finder 2e.mtprops
  src/main/resources/net/rptools/maptool/model/campaignProps/metric Stars Without Number.mtprops
  src/main/resources/net/rptools/maptool/model/campaignProps/metric Tunnels & Trolls - Deluxe.mtprops
Labels: feature

#5170 Only show drawing layer in Draw Explorer if it is not empty
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelTreeModel.java
Labels: bug

#5158 MTScript Drawing functions
  src/main/java/net/rptools/lib/io/PackedFile.java
  src/main/java/net/rptools/maptool/client/MapToolExpressionParser.java
  src/main/java/net/rptools/maptool/client/functions/ShapeFunctions.java
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelTreeCellRenderer.java
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawablesPanel.java
  src/main/java/net/rptools/maptool/client/ui/theme/Icons.java
  src/main/java/net/rptools/maptool/client/ui/theme/RessourceManager.java
  src/main/java/net/rptools/maptool/model/drawing/AbstractDrawing.java
  src/main/java/net/rptools/maptool/model/drawing/ExtendedGeneralPath_Double.java
  src/main/java/net/rptools/maptool/model/drawing/ShapeDrawable.java
  src/main/java/net/rptools/maptool/server/Mapper.java
  src/main/java/net/rptools/maptool/util/FunctionUtil.java
  src/main/proto/drawing_dto.proto
  src/main/resources/net/rptools/maptool/client/image/tool/drawpanel-arc.png
  src/main/resources/net/rptools/maptool/client/image/tool/drawpanel-cubic.png
  src/main/resources/net/rptools/maptool/client/image/tool/drawpanel-line2d.png
  src/main/resources/net/rptools/maptool/client/image/tool/drawpanel-path.png
  src/main/resources/net/rptools/maptool/client/image/tool/drawpanel-quad.png
  src/main/resources/net/rptools/maptool/client/image/tool/drawpanel-roundrect.png
  src/main/resources/net/rptools/maptool/client/image/tool/drawpanel-unknown.png
  src/main/resources/net/rptools/maptool/client/image/warning.svg
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#5162 Add StartupWMClass so MT windows are properly recognized on Linux.
  package/linux/launcher.desktop
Labels: bug, build-configuration

#5161 Windows uri
  build.gradle
  package/windows/main.wxs
Labels: feature

#5156 Add property default and reset js bindings
  src/main/java/net/rptools/maptool/client/script/javascript/api/JSAPIToken.java
  src/main/java/net/rptools/maptool/model/Token.java
Labels: bug

#5186 Campaign props export file type fix
  src/main/java/net/rptools/maptool/client/AppConstants.java
  src/main/java/net/rptools/maptool/client/swing/SwingUtil.java
  src/main/java/net/rptools/maptool/client/ui/MapToolFrame.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/resources/net/rptools/maptool/language/i18n_en.properties
Labels: bug

#5193 Fix the Arch build so assets are available again
  .github/workflows/publish.yml
Labels: bug, code-maintenance

#5181 Fix background and fog paints returned by getInfo("map")
  src/main/java/net/rptools/maptool/client/functions/getInfoFunction.java
Labels: bug

#5197 getNamespace for macro context
  src/main/java/net/rptools/maptool/client/MapToolMacroContext.java
Labels: feature

#5199 Bump com.github.jknack:handlebars-helpers from 4.3.1 to 4.4.0
  build.gradle
  src/main/java/net/rptools/maptool/util/HandlebarsUtil.java
Labels: dependencies

#5195 Disable focusable tooltips for RSyntaxTextAreas
  build.gradle
  src/main/java/net/rptools/maptool/client/swing/htmleditorsplit/HtmlEditorSplitGui.form
  src/main/java/net/rptools/maptool/client/ui/logger/LogConsoleFrame.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/dialog/MacroButtonDialogView.form
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/dialog/MacroEditorDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
Labels: bug

#5198 Add archives of the app-images as release assets
  .github/workflows/publish.yml
  build.gradle
Labels: feature, build-configuration

#5201 Update actions/cache to v4
  .github/workflows/publish.yml
  .github/workflows/verify-build.yml
Labels: build-configuration, code-maintenance, dependencies

#5203 Merge 1.16 Campaign Macro Export fix into develop
  src/main/java/net/rptools/maptool/client/AppConstants.java
  src/main/java/net/rptools/maptool/client/swing/SwingUtil.java
  src/main/java/net/rptools/maptool/client/ui/MapToolFrame.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/resources/net/rptools/maptool/language/i18n_en.properties
Labels: ignore-for-release-note

#5220 Fix null grassland asset ID
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/swing/ResourceLoader.java
  src/main/java/net/rptools/maptool/model/CampaignFactory.java
  src/main/java/net/rptools/maptool/model/ZoneFactory.java
Labels: bug

#5218 Port fix for hanging Gather Debug Information to 1.16
  src/main/java/net/rptools/maptool/client/ui/SysInfoDialog.java
Labels: bug

#5213 Fix Easy Connect handshake control flow once public key is requested
  clientserver/src/main/java/net/rptools/clientserver/simple/server/WebRTCServer.java
  src/main/java/net/rptools/maptool/server/ServerHandshake.java
Labels: bug

#5232 Merge Latest 1.16 changes into Develop
  clientserver/src/main/java/net/rptools/clientserver/simple/server/WebRTCServer.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/swing/ResourceLoader.java
  src/main/java/net/rptools/maptool/client/ui/SysInfoDialog.java
  src/main/java/net/rptools/maptool/model/CampaignFactory.java
  src/main/java/net/rptools/maptool/model/ZoneFactory.java
  src/main/java/net/rptools/maptool/server/ServerHandshake.java
Labels: ignore-for-release-note

#5227 Support strformat literals without passing args
  src/main/java/net/rptools/maptool/client/functions/StringFunctions.java
Labels: bug

#5230 Recognise empty files in addons with .mts suffix as text files
  src/main/java/net/rptools/maptool/model/Asset.java
Labels: bug

#5237 Add gradle version catalogue
  build.gradle
  clientserver/build.gradle
  gradle/libs.versions.toml
Labels: build-configuration, code-maintenance

#5244 Consolidate scattered protobuf versions
  build.gradle
  gradle/libs.versions.toml
Labels: code-maintenance

#5261 Register mockito as a java agent
  build.gradle
  buildSrc/shared.gradle
  clientserver/build.gradle
Labels: code-maintenance

#5264 Hide statsheet overlay when no statsheet visible, and overlay panel when no overlay is visible
  src/main/java/net/rptools/maptool/client/events/OverlayVisibilityChanged.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLOverlayManager.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLOverlayPanel.java
  src/main/java/net/rptools/maptool/client/ui/sheet/stats/StatSheet.java
Labels: feature, refactor, performance

#5269 Fix deadlock in 1.16.0.rc-1
  src/main/java/net/rptools/maptool/client/MapTool.java
Labels: bug

#5270 Fix deadlock in 1.16.0.rc-1 - release-1.16
  src/main/java/net/rptools/maptool/client/MapTool.java
Labels: bug

#5276 Merge 1.16 into develop
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
Labels: ignore-for-release-note

#5286 Updates to README as well as contributor doco
  CHANGE_LOG.md
  CONTRIBUTING.md
  README.md
  buildSrc/java-version.gradle
  buildSrc/shared.gradle
  doc/Code_Style_and_Guidelines.md
  doc/How_To_Install_JDK.md
  doc/How_To_Setup_Eclipse.md
  doc/How_To_Setup_UI_Tools.md
  doc/discord_100.webp
  doc/discord_wide.webp
  doc/maven-cmdline.txt
Labels: bug
