Repository RPTools/maptool, pull requests merged in 2025-05, with the labels that each got.

#5375 Allow MT Line Parser and JS Fetch to resolve lib: uri for macros
  src/main/java/net/rptools/maptool/client/MapToolExpressionParser.java
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/MapToolMacroContext.java
  src/main/java/net/rptools/maptool/client/functions/CallFunction.java
  src/main/java/net/rptools/maptool/client/functions/DefineMacroFunction.java
  src/main/java/net/rptools/maptool/client/functions/ExecFunction.java
  src/main/java/net/rptools/maptool/client/functions/MacroDialogFunctions.java
  src/main/java/net/rptools/maptool/client/functions/MacroFunctions.java
  src/main/java/net/rptools/maptool/client/functions/MacroLinkFunction.java
  src/main/java/net/rptools/maptool/client/functions/ParserPropertyFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenImage.java
  src/main/java/net/rptools/maptool/client/functions/TokenPropertyFunctions.java
  src/main/java/net/rptools/maptool/client/macro/MacroLocation.java
  src/main/java/net/rptools/maptool/client/macro/MacroLocationFactory.java
  src/main/java/net/rptools/maptool/client/macro/impl/SayMacro.java
  src/main/java/net/rptools/maptool/client/macro/impl/ToGMMacro.java
  src/main/java/net/rptools/maptool/client/swing/MapToolEventQueue.java
  src/main/java/net/rptools/maptool/model/MacroButtonProperties.java
  src/main/java/net/rptools/maptool/model/library/LibraryManager.java
  src/main/java/net/rptools/maptool/model/library/addon/AddOnLibrary.java
  src/main/java/net/rptools/maptool/model/library/token/LibraryToken.java
  src/main/java/net/rptools/maptool/model/library/token/LibraryTokenManager.java
  src/main/java/net/rptools/maptool/model/library/url/RequestHandler.java
  src/main/java/net/rptools/maptool/util/EventMacroUtil.java
  src/main/resources/net/rptools/maptool/client/html5/javascript/Console.js
  src/main/resources/net/rptools/maptool/client/html5/javascript/Replace_Submit.js
  src/main/resources/net/rptools/maptool/client/html5/javascript/XMLHttpRequest.js
  src/test/java/net/rptools/maptool/client/MapToolLineParserTest.java
  src/test/java/net/rptools/maptool/client/functions/GetRolledTest.java
  src/test/java/net/rptools/maptool/client/functions/UserDefinedMacroTest.java
  src/test/java/net/rptools/maptool/client/macro/MacroLocationFactory.java
  src/test/java/net/rptools/maptool/client/macro/MacroLocationTest.java
  src/test/java/net/rptools/maptool/model/TokenPropertiesTest.java
Labels: bug

#5406 Generate walls from UVTT line-of-sight data
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/uvtt/UvttLineOfSightPromptDialog.java
  src/main/java/net/rptools/maptool/client/ui/uvtt/UvttLineOfSightPromptView.form
  src/main/java/net/rptools/maptool/client/ui/uvtt/UvttLineOfSightPromptView.java
  src/main/java/net/rptools/maptool/client/utilities/DungeonDraftImporter.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#5411 Add bounds to numeric preferences
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/swing/StatusPanel.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
Labels: feature, refactor

#5428 Token anchor offset correction on paste
  src/main/java/net/rptools/maptool/client/AppActions.java
Labels: bug

#5431 Rework Edit Token dialog to suit smaller screens and promote better organization
  src/main/java/net/rptools/maptool/client/swing/AbeillePanel.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutPanelHelper.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.form
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#5426 setPenColor and setFillColor now set respective paints to null
  src/main/java/net/rptools/maptool/client/functions/DrawingSetterFunctions.java
Labels: bug

#5434 Fix Zoom status disappearing
  src/main/java/net/rptools/maptool/client/swing/ZoomStatusBar.java
Labels: bug

#5435 Fix preferences dialog width depending on confg file path
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/theme/ThemeSupport.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#5440 Add issue type to the issue forms
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/code_improvement.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: code-maintenance

#5432 Generic dialog fixes
  src/main/java/net/rptools/maptool/client/swing/GenericDialog.java
  src/main/java/net/rptools/maptool/client/swing/SwingUtil.java
Labels: feature

#5437 Fix errors when editing Native Size or Free Size tokens
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutPanelHelper.java
Labels: bug

#5442 Load content into WebViews through URLs
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLWebViewManager.java
Labels: bug

#5444 New markdownToHtml() function optional parameter for user selection of flexmark extensions
  src/main/java/net/rptools/maptool/client/functions/MarkDownFunctions.java
Labels: feature

#5451 Make AssetLoader.requestAsset idempotent
  src/main/java/net/rptools/maptool/model/AssetLoader.java
  src/main/java/net/rptools/maptool/model/AssetManager.java
Labels: bug

#5450 return drawn templates' template type and size
  src/main/java/net/rptools/maptool/client/functions/DrawingFunctions.java
Labels: bug

#5452 Merge 1.16 changes into 1.17
  src/main/java/net/rptools/maptool/model/AssetLoader.java
  src/main/java/net/rptools/maptool/model/AssetManager.java
Labels: ignore-for-release-note

#5453 Stop walls from coming back from the dead
  src/main/java/net/rptools/maptool/client/swing/walls/WallConfigurationController.java
  src/main/java/net/rptools/maptool/client/tool/WallTopologyTool.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/MovementBlockingTopology.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/model/converters/WallTopologyConverter.java
  src/main/java/net/rptools/maptool/model/topology/Wall.java
  src/main/java/net/rptools/maptool/model/topology/WallTopology.java
Labels: feature

#5456 Only use new help text for sights, lights, and auras
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#5464 Relieve i18n from managing menu accelerator keys
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/MapToolUtil.java
  src/main/java/net/rptools/maptool/client/functions/FogOfWarFunctions.java
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
  src/main/java/net/rptools/maptool/client/tool/StampTool.java
  src/main/java/net/rptools/maptool/client/ui/AbstractTokenPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/TokenPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/commandpanel/CommandPanel.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/dialog/MacroEditorDialog.java
  src/main/java/net/rptools/maptool/language/I18N.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug, code-maintenance

#5467 Logging fix to capture java.util.logging calls
  build.gradle
  src/main/java/net/rptools/maptool/client/LaunchInstructions.java
Labels: bug

#5461 Fix for API not working when navigating to new page in frame5/dialog5…
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/functions/MacroDialogFunctions.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLContent.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLDialog.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLFrame.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLFrameFactory.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLJFXPanel.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLOverlayManager.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLOverlayPanel.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLPane.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLPanel.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLPanelInterface.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLWebViewManager.java
  src/main/java/net/rptools/maptool/client/ui/sheet/stats/StatSheet.java
  src/main/java/net/rptools/maptool/model/Asset.java
  src/main/java/net/rptools/maptool/model/library/url/LibraryURLConnection.java
  src/main/java/net/rptools/maptool/util/HTMLUtil.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#5490 Various fixes for LibGDX renderer
  src/main/java/net/rptools/lib/image/ImageUtil.java
  src/main/java/net/rptools/maptool/client/ScreenPoint.java
  src/main/java/net/rptools/maptool/client/ui/Scale.java
  src/main/java/net/rptools/maptool/client/ui/exportdialog/ExportDialog.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttons/MacroButton.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneViewModel.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/GdxRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/HaloRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/RenderHelper.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/SelectionRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/TokenPosition.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/tokenRender/FacingArrowRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/tokenRender/TokenRenderer.java
Labels: bug

#5491 Text maintenance
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#5482 Bug fixes for scrolling status bar
  src/main/java/net/rptools/maptool/client/swing/StatusPanel.java
Labels: bug

#5497 Fix flickering with selection box and other stuff
  src/main/java/net/rptools/maptool/client/ui/MapToolFrame.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/AreaRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/GdxRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/GridRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/TokenOverlayRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/ZoneCache.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/label/TextRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/LumensRenderer.java
  src/main/resources/net/rptools/maptool/client/maptool.atlas
  src/main/resources/net/rptools/maptool/client/maptool.png
Labels: bug

#5504 1.17 - Fix ClassCastException when draging snap-to-grid token on gridless map
  src/main/java/net/rptools/maptool/model/Path.java
  src/test/java/net/rptools/maptool/model/PathTest.java
Labels: bug

#5510 Various fixes for recent renderer changes
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneViewModel.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/RenderHelper.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/tokenRender/FacingArrowRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/tokenRender/TokenRenderer.java
  src/main/java/net/rptools/maptool/model/Token.java
Labels: bug, performance

#5509 DrawPanelTree information improvements for templates
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelTreeCellRenderer.java
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelTreeModel.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#5498 refactor and and vue hack
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/functions/MacroDialogFunctions.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLContent.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLDialog.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLFrame.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLFrameFactory.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLJFXPanel.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLOverlayManager.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLOverlayPanel.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLPane.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLPanel.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLPanelInterface.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLWebViewManager.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/HTMLContent.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/InjectContentSecurityPolicy.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/InjectJSAPi.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/InjectUrlBase.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/PreprocessorOperations.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/VueHack.java
  src/main/java/net/rptools/maptool/client/ui/sheet/stats/StatSheet.java
  src/main/java/net/rptools/maptool/model/library/url/LibraryURLConnection.java
Labels: feature

#5518 Another round of renderer fixes
  src/main/java/net/rptools/lib/CodeTimer.java
  src/main/java/net/rptools/maptool/client/ui/Scale.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/panels/MenuButtonsPanel.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneViewModel.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/GdxRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/tokenRender/TokenRenderer.java
Labels: bug

#5519 Fix token halo color to not be set by default
  src/main/java/net/rptools/maptool/client/functions/TokenHaloFunction.java
  src/main/java/net/rptools/maptool/client/ui/tokenpanel/InitiativeListCellRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/GdxRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/HaloRenderer.java
  src/main/java/net/rptools/maptool/model/Token.java
Labels: bug

#5520 Remove i18n files without country codes
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/i18n_ach.properties
  src/main/resources/net/rptools/maptool/language/i18n_cs.properties
  src/main/resources/net/rptools/maptool/language/i18n_da.properties
  src/main/resources/net/rptools/maptool/language/i18n_de.properties
  src/main/resources/net/rptools/maptool/language/i18n_en.properties
  src/main/resources/net/rptools/maptool/language/i18n_es.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr.properties
  src/main/resources/net/rptools/maptool/language/i18n_it.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru.properties
  src/main/resources/net/rptools/maptool/language/i18n_si.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh.properties
Labels: code-maintenance

#5521 Further adjustments to Startup tab of Preferences dialog
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#5523 Hide LibGDX button behind developer preference
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/AutoSaveManager.java
  src/main/java/net/rptools/maptool/client/DeveloperOptions.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
  src/main/java/net/rptools/maptool/client/tool/StampTool.java
  src/main/java/net/rptools/maptool/client/ui/ToolbarPanel.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/PartitionedDrawableRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/walker/astar/AbstractAStarWalker.java
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/util/preferences/BasicPreference.java
  src/main/java/net/rptools/maptool/util/preferences/NumericPreference.java
  src/main/java/net/rptools/maptool/util/preferences/Preference.java
  src/main/java/net/rptools/maptool/util/preferences/PreferenceStore.java
  src/main/java/net/rptools/maptool/util/preferences/PreferenceType.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#5526 Updated credits to add Rod T
  src/main/resources/net/rptools/maptool/client/credits.html
Labels: ignore-for-release-note

#5525 Revert "refactor and and vue hack"
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/functions/MacroDialogFunctions.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLContent.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLDialog.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLFrame.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLFrameFactory.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLJFXPanel.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLOverlayManager.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLOverlayPanel.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLPane.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLPanel.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLPanelInterface.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLWebViewManager.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/HTMLContent.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/InjectContentSecurityPolicy.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/InjectJSAPi.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/InjectUrlBase.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/PreprocessorOperations.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/content/VueHack.java
  src/main/java/net/rptools/maptool/client/ui/sheet/stats/StatSheet.java
  src/main/java/net/rptools/maptool/model/library/url/LibraryURLConnection.java
Labels: ignore-for-release-note
