Repository RPTools/maptool, pull requests merged in 2025-04, with the labels that each got.

#5351 Merge release-1.17 into develop
  src/main/java/net/rptools/maptool/client/functions/StringFunctions.java
Labels: ignore-for-release-note

#5345 Update parser library to get its unicode-safe parser
  gradle/libs.versions.toml
  src/test/java/net/rptools/dicelib/expression/ExpressionParserTest.java
Labels: bug

#5344 Improved mouse support for walls
  src/main/java/net/rptools/maptool/client/tool/WallTopologyTool.java
  src/main/java/net/rptools/maptool/client/tool/rig/WallTopologyRig.java
  src/main/java/net/rptools/maptool/client/ui/MapToolFrame.java
  src/main/java/net/rptools/maptool/model/topology/WallTopology.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#5359 Retain null in json.indent
  src/main/java/net/rptools/maptool/client/functions/json/JSONMacroFunctions.java
Labels: bug

#5360 Token layout tab - nerfed version
  src/main/java/net/rptools/lib/MathUtil.java
  src/main/java/net/rptools/lib/image/ImageUtil.java
  src/main/java/net/rptools/maptool/client/AppConstants.java
  src/main/java/net/rptools/maptool/client/functions/TokenImage.java
  src/main/java/net/rptools/maptool/client/functions/TokenPropertyFunctions.java
  src/main/java/net/rptools/maptool/client/swing/SpinnerSliderPaired.java
  src/main/java/net/rptools/maptool/client/tool/StampTool.java
  src/main/java/net/rptools/maptool/client/ui/AbstractTokenPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutPanel.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutPanelHelper.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutRenderPanel.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.form
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/HaloRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/TokenPosition.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/tokenRender/FacingArrowRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/tokenRender/TokenRenderer.java
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/util/GraphicsUtil.java
  src/main/proto/data_transfer_objects.proto
  src/main/resources/net/rptools/maptool/client/image/scale.svg
  src/main/resources/net/rptools/maptool/client/image/scaleHor.svg
  src/main/resources/net/rptools/maptool/client/image/scaleVert.svg
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/macro_descriptions/i18n.properties
Labels: feature

#5104 Token class updates to accommodate new layout features
  src/main/java/net/rptools/lib/MathUtil.java
  src/main/java/net/rptools/lib/image/ImageUtil.java
  src/main/java/net/rptools/maptool/client/AppConstants.java
  src/main/java/net/rptools/maptool/client/functions/TokenImage.java
  src/main/java/net/rptools/maptool/client/functions/TokenPropertyFunctions.java
  src/main/java/net/rptools/maptool/client/swing/SpinnerSliderPaired.java
  src/main/java/net/rptools/maptool/client/tool/StampTool.java
  src/main/java/net/rptools/maptool/client/ui/AbstractTokenPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutPanel.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutPanelHelper.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutRenderPanel.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.form
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/HaloRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/TokenPosition.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/tokenRender/FacingArrowRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/tokenRender/TokenRenderer.java
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/util/GraphicsUtil.java
  src/main/proto/data_transfer_objects.proto
  src/main/resources/net/rptools/maptool/client/image/scale.svg
  src/main/resources/net/rptools/maptool/client/image/scaleHor.svg
  src/main/resources/net/rptools/maptool/client/image/scaleVert.svg
  src/main/resources/net/rptools/maptool/language/i18n.properties
  src/main/resources/net/rptools/maptool/language/macro_descriptions/i18n.properties
Labels: feature, claimed, refactor

#5368 Plural/Possessive emote fix
  src/main/java/net/rptools/maptool/client/macro/MacroManager.java
  src/main/java/net/rptools/maptool/client/macro/impl/EmotePossessiveMacro.java
  src/main/java/net/rptools/maptool/util/MessageUtil.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: pedantic, refactor, code-maintenance

#5369 New preference - open macro editor for new macros.
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttongroups/ButtonGroupPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/buttons/MacroButtonPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/dialog/MacroEditorDialog.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.form
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#5381 Conflict resolution
  src/main/resources/net/rptools/maptool/language/i18n_cs_CZ.properties
  src/main/resources/net/rptools/maptool/language/i18n_da_DK.properties
  src/main/resources/net/rptools/maptool/language/i18n_de_DE.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_AU.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_GB.properties
  src/main/resources/net/rptools/maptool/language/i18n_es_ES.properties
  src/main/resources/net/rptools/maptool/language/i18n_fr_FR.properties
  src/main/resources/net/rptools/maptool/language/i18n_it_IT.properties
  src/main/resources/net/rptools/maptool/language/i18n_ja_JP.properties
  src/main/resources/net/rptools/maptool/language/i18n_nl_NL.properties
  src/main/resources/net/rptools/maptool/language/i18n_pl_PL.properties
  src/main/resources/net/rptools/maptool/language/i18n_pt_BR.properties
  src/main/resources/net/rptools/maptool/language/i18n_ru_RU.properties
  src/main/resources/net/rptools/maptool/language/i18n_si_LK.properties
  src/main/resources/net/rptools/maptool/language/i18n_sv_SE.properties
  src/main/resources/net/rptools/maptool/language/i18n_uk_UA.properties
  src/main/resources/net/rptools/maptool/language/i18n_zh_CN.properties
Labels: ignore-for-release-note

#5383 Scrolling status bar messages and associated app preferences
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/swing/StatusPanel.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.form
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug
