Repository RPTools/maptool, pull requests merged in 2025-07, with the labels that each got.

#5664 Reset tooltips for non-template DrawnElements
  src/main/java/net/rptools/maptool/client/ui/drawpanel/DrawPanelTreeCellRenderer.java
Labels: bug

#5667 Fix lib token @ this
  src/main/java/net/rptools/maptool/client/functions/MacroLinkFunction.java
Labels: bug

#5668 Integrated label and tooltip strings with preferences.
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/util/preferences/BasicPreference.java
  src/main/java/net/rptools/maptool/util/preferences/Preference.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature

#5647 Enchanced Token Initiative sorting.
  src/main/java/net/rptools/maptool/model/InitiativeList.java
Labels: bug, feature

#5686 Fix display of PreferenceDialog
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
Labels: bug

#5687 For linear drawing tools, force the foreground mode to be solid
  src/main/java/net/rptools/maptool/client/tool/drawing/DrawingTool.java
Labels: bug

#5688 For linear drawing tools, force the foreground mode to be solid
  src/main/java/net/rptools/maptool/client/tool/drawing/DrawingTool.java
Labels: bug

#5705 Update 1.18 release branch with last 1.17 fix
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/model/Token.java
Labels: bug

#5710 1.18 - fix for untransformed token VBL
  src/main/java/net/rptools/maptool/client/functions/Topology_Functions.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/tokenRender/TokenRenderer.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/model/Zone.java
  src/main/java/net/rptools/maptool/util/TokenUtil.java
Labels: bug

#5708 1.18 - fix for lib: prefix handling
  src/main/java/net/rptools/maptool/client/MapToolLineParser.java
  src/main/java/net/rptools/maptool/client/functions/DefineMacroFunction.java
  src/main/java/net/rptools/maptool/client/functions/ParserPropertyFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenPropertyFunctions.java
  src/main/java/net/rptools/maptool/client/macro/impl/SayMacro.java
  src/main/java/net/rptools/maptool/client/macro/impl/ToGMMacro.java
  src/main/java/net/rptools/maptool/model/library/Library.java
  src/main/java/net/rptools/maptool/model/library/addon/AddOnLibrary.java
  src/main/java/net/rptools/maptool/model/library/builtin/ClassPathAddOnLibrary.java
  src/main/java/net/rptools/maptool/model/library/builtin/MapToolBuiltInLibrary.java
  src/main/java/net/rptools/maptool/model/library/token/LibraryToken.java
  src/main/java/net/rptools/maptool/model/library/token/LibraryTokenManager.java
Labels: bug

#5714 Fix token topology transfers and other issues with token bounds
  src/main/java/net/rptools/lib/image/ImageUtil.java
  src/main/java/net/rptools/maptool/client/functions/TokenLocationFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenMoveFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenPropertyFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenSightFunctions.java
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
  src/main/java/net/rptools/maptool/client/tool/StampTool.java
  src/main/java/net/rptools/maptool/client/ui/exportdialog/ExportDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenTopologyPanel.java
  src/main/java/net/rptools/maptool/client/ui/zone/FogUtil.java
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneViewModel.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/GdxRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/TokenOverlayRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/label/TokenLabelRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/vbl/TokenVBL.java
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/model/Zone.java
Labels: bug

#5729 Token layout nerfed fix for #5728
  src/main/java/net/rptools/maptool/client/swing/SpinnerSliderPaired.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutPanelHelper.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutRenderPanel.java
Labels: bug
