Repository RPTools/maptool, pull requests merged in 2025-01, with the labels that each got.

#5135 Restore circular "unlimited" vision for grid sights
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/GridlessGrid.java
Labels: bug, performance

#5076 Handle rptools-maptool: URI for quick-join links
  .gitignore
  build.gradle
  doc/How_To_Setup_UI_Tools.md
  package/linux/launcher.desktop
  src/main/java/net/rptools/clientserver/ConnectionFactory.java
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/MapToolRegistry.java
  src/main/java/net/rptools/maptool/client/MapToolServiceFinder.java
  src/main/java/net/rptools/maptool/client/RemoteServerConfig.java
  src/main/java/net/rptools/maptool/client/ServerAddress.java
  src/main/java/net/rptools/maptool/client/ui/connectioninfodialog/ConnectionInfoDialog.java
  src/main/java/net/rptools/maptool/client/ui/connectioninfodialog/ConnectionInfoDialogView.form
  src/main/java/net/rptools/maptool/client/ui/connectioninfodialog/ConnectionInfoDialogView.java
  src/main/java/net/rptools/maptool/client/ui/connecttoserverdialog/ConnectToServerDialog.java
  src/main/java/net/rptools/maptool/client/ui/connecttoserverdialog/ConnectToServerDialogPreferences.java
  src/main/java/net/rptools/maptool/model/player/LocalPlayer.java
  src/main/java/net/rptools/maptool/server/MapToolServer.java
  src/main/java/net/rptools/maptool/util/NetUtil.java
  src/main/resources/net/rptools/maptool/client/ui/forms/addResourcesDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/adjustBoardControlPanel.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/adjustGridControlPanel.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/adjustGridDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/basicCharacterSheet_unused.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/campaignItemList.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/campaignPropertiesDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/colorPanel.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/connectToServerDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/connectionInfoDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/editLabelDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/editLookupTablePanel.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/exportDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/layerSelectionDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/lightSourceDialog_unused.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/lookupTablePanel.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/macroButtonDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/mapPropertiesDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/newTokenDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/preferencesDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/startServerDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/tokenNotesDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/tokenPropertiesDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/tokenPropertiesManagementPanel.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/transferProgressDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/updateRepoDialog.xml
  src/main/resources/net/rptools/maptool/client/ui/forms/visionDialog_unused.xml
  src/main/resources/net/rptools/maptool/language/i18n_en.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_AU.properties
  src/main/resources/net/rptools/maptool/language/i18n_en_GB.properties
Labels: feature

#5131 Bump upnplib to latest version
  build.gradle
Labels: bug
