Repository RPTools/maptool, pull requests merged in 2025-06, with the labels that each got.

#5515 New MTScript get table entries functions
  src/main/java/net/rptools/maptool/client/functions/LookupTableFunction.java
Labels: feature

#5536 Replace bcmail-jdk15on with bcmail-jdk18on, and update to 1.81
  gradle/libs.versions.toml
Labels: dependencies

#5537 Preserve user-specified order of sights, lights, and auras
  src/main/java/net/rptools/maptool/client/functions/FindTokenFunctions.java
  src/main/java/net/rptools/maptool/client/functions/TokenLightFunctions.java
  src/main/java/net/rptools/maptool/client/functions/getInfoFunction.java
  src/main/java/net/rptools/maptool/client/ui/AbstractTokenPopupMenu.java
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/model/AttachedLightSource.java
  src/main/java/net/rptools/maptool/model/Campaign.java
  src/main/java/net/rptools/maptool/model/CampaignProperties.java
  src/main/java/net/rptools/maptool/model/CategorizedLights.java
  src/main/java/net/rptools/maptool/model/Lights.java
  src/main/java/net/rptools/maptool/model/Sights.java
  src/main/java/net/rptools/maptool/model/Token.java
  src/main/java/net/rptools/maptool/util/AuraSyntax.java
  src/main/java/net/rptools/maptool/util/LightSyntax.java
  src/main/java/net/rptools/maptool/util/SightSyntax.java
Labels: feature

#5539 Update upnplib to 1.2.0
  gradle/libs.versions.toml
Labels: code-maintenance, dependencies

#5549 Update json-smart
  build.gradle
  gradle/libs.versions.toml
Labels: code-maintenance, dependencies

#5551 Remove io.grpc:grpc-protobuf dependency
  build.gradle
  gradle/libs.versions.toml
Labels: code-maintenance, dependencies

#5569 Catch and log all errors during startup
  src/main/java/net/rptools/maptool/client/LaunchInstructions.java
Labels: bug, code-maintenance

#5507 Ability to load preferred font settings before starting FlatLaf
  src/main/java/net/rptools/maptool/client/AppPreferences.java
  src/main/java/net/rptools/maptool/client/swing/FontChooser.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/theme/ThemeFontPreferences.java
  src/main/java/net/rptools/maptool/client/ui/theme/ThemeFontPreferencesPanel.form
  src/main/java/net/rptools/maptool/client/ui/theme/ThemeFontPreferencesPanel.java
  src/main/java/net/rptools/maptool/client/ui/theme/ThemeFontTools.java
  src/main/java/net/rptools/maptool/client/ui/theme/ThemeSupport.java
  src/main/resources/net/rptools/maptool/client/ui/themes/modelUserTheme.properties
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug, feature

#5588 Update cipher algorithms
  src/main/java/net/rptools/maptool/util/cipher/CipherUtil.java
Labels: code-maintenance

#5592 Reduce workflow permissions and other fixes
  .github/dependabot.yml
  .github/workflows/nightly-publish.yml
  .github/workflows/publish.yml
  .github/workflows/verify-build.yml
Labels: code-maintenance, ignore-for-release-note

#5601 Fix logger initialization
  src/main/java/net/rptools/maptool/client/LaunchInstructions.java
Labels: bug

#5605 Force anchor position to the cell center for snap-to-grid movement
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/java/net/rptools/maptool/model/Token.java
Labels: bug

#5609 Always populate token properties table in Edit Token dialog
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
Labels: bug

#5610 Consistently resolve the FlatLaf.properties file
  src/main/java/net/rptools/maptool/client/ui/theme/ThemeFontTools.java
Labels: bug

#5614 Fix spurious theme change warning on preferences close
  src/main/java/net/rptools/maptool/client/swing/FontChooser.java
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialog.java
  src/main/java/net/rptools/maptool/client/ui/theme/ThemeFontPreferences.java
Labels: bug

#5581 Grid Renderer - Improved appearance of grids
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/AppState.java
  src/main/java/net/rptools/maptool/client/ui/zone/gdx/GridRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/GridRenderer.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/HaloRenderer.java
  src/main/java/net/rptools/maptool/model/HexGrid.java
  src/main/java/net/rptools/maptool/model/IsometricGrid.java
  src/main/java/net/rptools/maptool/model/SquareGrid.java
  src/main/java/net/rptools/maptool/model/Zone.java
Labels: feature

#5634 Revert "Bump com.github.weisj:jsvg from 1.4.0 to 2.0.0"
  gradle/libs.versions.toml
Labels: dependencies

#5623 Generic dialogue rewrite
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/java/net/rptools/maptool/client/MapTool.java
  src/main/java/net/rptools/maptool/client/swing/ButtonKind.java
  src/main/java/net/rptools/maptool/client/swing/GenericDialog.java
  src/main/java/net/rptools/maptool/client/swing/GenericDialogFactory.java
  src/main/java/net/rptools/maptool/client/ui/addresource/AddResourceDialog.java
  src/main/java/net/rptools/maptool/client/ui/addresource/AddResourcesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/CampaignPropertiesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/campaignproperties/TokenPropertiesManagementPanelView.form
  src/main/java/net/rptools/maptool/client/ui/connecttoserverdialog/ConnectToServerDialog.java
  src/main/java/net/rptools/maptool/client/ui/connecttoserverdialog/ConnectToServerDialogView.form
  src/main/java/net/rptools/maptool/client/ui/preferencesdialog/PreferencesDialogView.form
  src/main/java/net/rptools/maptool/client/ui/startserverdialog/StartServerDialog.java
  src/main/java/net/rptools/maptool/client/ui/startserverdialog/StartServerDialogView.form
  src/main/java/net/rptools/maptool/client/ui/token/dialog/create/NewTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/create/NewTokenDialogView.form
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/EditTokenDialog.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenLayoutPanelHelper.java
  src/main/java/net/rptools/maptool/client/ui/token/dialog/edit/TokenPropertiesDialog.form
  src/main/java/net/rptools/maptool/client/ui/transferprogressdialog/TransferProgressDialog.java
  src/main/java/net/rptools/maptool/client/ui/transferprogressdialog/TransferProgressDialogView.form
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: feature, claimed, refactor, performance, code-maintenance

#5621 Refresh map when assets are loaded
  src/main/java/net/rptools/maptool/client/ui/zone/ZoneViewModel.java
  src/main/java/net/rptools/maptool/client/ui/zone/renderer/ZoneRenderer.java
Labels: bug

#5645 Fix mangled text after JSoup parsing
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLContent.java
  src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLWebViewManager.java
Labels: bug

#5641 Scrolling status performance tweak
  src/main/java/net/rptools/maptool/client/swing/StatusPanel.java
Labels: feature

#5649 Apply flat labels to initiative panel
  src/main/java/net/rptools/maptool/client/swing/label/FlatImageLabel.java
  src/main/java/net/rptools/maptool/client/ui/tokenpanel/InitiativeListCellRenderer.java
Labels: feature

#5652 Fix capitalization for Run Macro button i18n key
  src/main/java/net/rptools/maptool/client/ui/macrobuttons/dialog/MacroButtonDialogView.form
Labels: bug, code-maintenance

#5653 Fix get macro location
  src/main/java/net/rptools/maptool/client/functions/MacroFunctions.java
  src/main/java/net/rptools/maptool/client/macro/MacroLocation.java
  src/main/java/net/rptools/maptool/client/macro/MacroLocationFactory.java
  src/test/java/net/rptools/maptool/client/macro/MacroLocationFactory.java
  src/test/java/net/rptools/maptool/client/macro/MacroLocationTest.java
Labels: bug
