Repository RPTools/maptool, pull requests merged in 2025-03, with the labels that each got.

#5294 Add logic to delete old nightly builds and tags
  .github/workflows/nightly-publish.yml
Labels: build-configuration

#5303 Disable escaping of HTML characters in json.indent()
  src/main/java/net/rptools/maptool/client/functions/json/JSONMacroFunctions.java
Labels: bug

#5309 1.16 - Fix bad FoW check in PointerTool
  src/main/java/net/rptools/maptool/client/tool/PointerTool.java
  src/main/java/net/rptools/maptool/client/tool/StampTool.java
Labels: bug

#5310 Fix hex grid dimensions when reading from GridDto
  src/main/java/net/rptools/maptool/model/Grid.java
  src/main/java/net/rptools/maptool/model/HexGrid.java
Labels: bug

#5315 1.16 - Make tooltips show again for drawing tools, fog of war tools, and topology tools
  src/main/java/net/rptools/maptool/client/tool/drawing/AbstractDrawingLikeTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/AbstractTemplateTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/DrawingTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/ExposeTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/TopologyTool.java
Labels: bug

#5314 1.16 - fix map dragging for drawing tools and expose tools
  src/main/java/net/rptools/maptool/client/tool/drawing/DrawingTool.java
  src/main/java/net/rptools/maptool/client/tool/drawing/ExposeTool.java
Labels: bug

#5317 Fix with repository export when encountering missing asset.
  src/main/java/net/rptools/maptool/client/AppActions.java
  src/main/resources/net/rptools/maptool/language/i18n.properties
Labels: bug

#5318 Update credits
  src/main/resources/net/rptools/maptool/client/credits.html
Labels: code-maintenance

#5320 Exclude all bin/ directories from git source control
  .gitignore
Labels: code-maintenance
